import type { ScopeTag } from '../projects/index.js';
export type RateCardSourceLayer = 'KERF_SEED' | 'TENANT_MEMORY' | 'PROJECT_ACTUAL';
export interface KerfDivision { readonly code: string; readonly label: string; }
export interface TenantRateCardLine { readonly cost_code: string; readonly scope_tag: ScopeTag; readonly label: string; readonly kerf_division: KerfDivision; readonly uom: string; readonly unit_cents: number; readonly source_layer: RateCardSourceLayer; readonly review_required: boolean; readonly keywords: readonly string[]; readonly source_ref: string; readonly ricardo_included?: boolean; readonly ricardo_quantity?: number | null; readonly ricardo_sell_total_cents?: number | null; readonly ricardo_cost_total_cents?: number | null; }
export interface RateCardMatchInput { readonly tenantId: string; readonly scopeTag: ScopeTag; readonly description: string; readonly uom: string; readonly lineId?: string | null; readonly rateCard?: readonly TenantRateCardLine[]; }
export const RICARDO_FILLED_EXPECTED = {
  summary_sell_total_cents: 18_249_889,
  row_rounded_sell_total_cents: 18_249_890,
  summary_cost_total_cents: 11_862_428,
  row_rounded_cost_total_cents: 11_862_429,
  included_line_count: 46,
} as const;
const RICARDO_FILLED_RATE_CARD: readonly TenantRateCardLine[] = [
  {"cost_code": "GC-001", "scope_tag": "millwork", "label": "Project management & supervision", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "WK", "unit_cents": 48677, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["project", "management", "supervision"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-001", "ricardo_included": true, "ricardo_quantity": 4.0, "ricardo_sell_total_cents": 194708, "ricardo_cost_total_cents": 126560},
  {"cost_code": "GC-002", "scope_tag": "millwork", "label": "Site protection — floors/dust/zipwall", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "LS", "unit_cents": 118652, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["site", "protection", "floors", "dust", "zipwall"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-002", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 116843, "ricardo_cost_total_cents": 75948},
  {"cost_code": "GC-003", "scope_tag": "millwork", "label": "Daily cleanup & protection upkeep", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "WK", "unit_cents": 18680, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["daily", "cleanup", "protection", "upkeep"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-003", "ricardo_included": true, "ricardo_quantity": 4.0, "ricardo_sell_total_cents": 71102, "ricardo_cost_total_cents": 46216},
  {"cost_code": "GC-004", "scope_tag": "millwork", "label": "Final clean & punch list", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "LS", "unit_cents": 102345, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["final", "clean", "punch", "list"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-004", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 100535, "ricardo_cost_total_cents": 65348},
  {"cost_code": "GC-005", "scope_tag": "millwork", "label": "Dumpster — 10/12 yd", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "EA", "unit_cents": 106000, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["dumpster"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-005", "ricardo_included": true, "ricardo_quantity": 2.0, "ricardo_sell_total_cents": 212000, "ricardo_cost_total_cents": 137800},
  {"cost_code": "GC-006", "scope_tag": "millwork", "label": "Trailer load — haul to dump", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "EA", "unit_cents": 63403, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["trailer", "load", "haul", "dump"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "GC-007", "scope_tag": "millwork", "label": "Portable toilet", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "MO", "unit_cents": 30169, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["portable", "toilet"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "GC-008", "scope_tag": "millwork", "label": "Temporary power / generator", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "MO", "unit_cents": 40769, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["temporary", "power", "generator"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "GC-009", "scope_tag": "millwork", "label": "Permit running & inspection coordination", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "LS", "unit_cents": 73015, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["permit", "running", "inspection", "coordination"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "GC-010", "scope_tag": "millwork", "label": "Permit fees — pass-through at cost", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "LS", "unit_cents": 0, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["permit", "fees", "pass", "through", "cost"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-010"},
  {"cost_code": "GC-011", "scope_tag": "millwork", "label": "Plans / engineering coordination", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "LS", "unit_cents": 48677, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["plans", "engineering", "coordination"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-011", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "GC-012", "scope_tag": "millwork", "label": "Material procurement & staging", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "LS", "unit_cents": 63280, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["procurement", "staging"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-012", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "GC-013", "scope_tag": "millwork", "label": "Mobilization / demobilization", "kerf_division": {"code": "01", "label": "General Conditions"}, "uom": "LS", "unit_cents": 55249, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["mobilization", "demobilization"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/GC-013", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-001", "scope_tag": "demolition", "label": "Kitchen demo — full (cabinets/counters/splash)", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "LS", "unit_cents": 263102, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["kitchen", "demo", "full", "cabinets", "counters", "splash"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-001", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 255865, "ricardo_cost_total_cents": 166312},
  {"cost_code": "DM-002", "scope_tag": "demolition", "label": "Bathroom demo — full gut", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "EA", "unit_cents": 271255, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["bathroom", "demo", "full", "gut"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-003", "scope_tag": "demolition", "label": "Cabinet/vanity removal only", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "LF", "unit_cents": 5841, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["cabinet", "vanity", "removal"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-004", "scope_tag": "demolition", "label": "Countertop removal — stone", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "SF", "unit_cents": 1258, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["countertop", "removal", "stone"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-005", "scope_tag": "demolition", "label": "Flooring removal — wood/engineered", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "SF", "unit_cents": 408, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["flooring", "removal", "wood", "engineered"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-006", "scope_tag": "demolition", "label": "Flooring removal — tile + thinset grind", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "SF", "unit_cents": 652, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["flooring", "removal", "tile", "thinset", "grind"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-006", "ricardo_included": true, "ricardo_quantity": 250.0, "ricardo_sell_total_cents": 163077, "ricardo_cost_total_cents": 106000},
  {"cost_code": "DM-007", "scope_tag": "demolition", "label": "Flooring removal — carpet & pad", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "SF", "unit_cents": 122, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["flooring", "removal", "carpet", "pad"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-008", "scope_tag": "demolition", "label": "Wall removal — non-bearing", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "LF", "unit_cents": 23548, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["wall", "removal", "non", "bearing"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-009", "scope_tag": "demolition", "label": "Wall removal — bearing (structural by Div 06)", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "LF", "unit_cents": 63403, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["wall", "removal", "bearing", "structural", "div"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-010", "scope_tag": "demolition", "label": "Drywall selective demo", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "SF", "unit_cents": 520, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["drywall", "selective", "demo"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-010", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-011", "scope_tag": "demolition", "label": "Baseboard/trim removal", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "LF", "unit_cents": 292, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["baseboard", "trim", "removal"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-011", "ricardo_included": true, "ricardo_quantity": 70.0, "ricardo_sell_total_cents": 19178, "ricardo_cost_total_cents": 12466},
  {"cost_code": "DM-012", "scope_tag": "demolition", "label": "Door & frame removal", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "EA", "unit_cents": 9735, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["door", "frame", "removal"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-012", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-013", "scope_tag": "demolition", "label": "Window removal", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "EA", "unit_cents": 21102, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["window", "removal"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-013", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-014", "scope_tag": "demolition", "label": "Fixture/appliance disconnect & removal", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "EA", "unit_cents": 9735, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["fixture", "appliance", "disconnect", "removal"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-014", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DM-015", "scope_tag": "demolition", "label": "Concrete sawcut & removal", "kerf_division": {"code": "02", "label": "Demolition"}, "uom": "SF", "unit_cents": 1957, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["concrete", "sawcut", "removal"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DM-015", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CN-001", "scope_tag": "foundation", "label": "Footing excavation & form", "kerf_division": {"code": "03", "label": "Concrete & Foundation"}, "uom": "LF", "unit_cents": 7338, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["footing", "excavation", "form"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CN-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CN-002", "scope_tag": "foundation", "label": "Concrete footing pour", "kerf_division": {"code": "03", "label": "Concrete & Foundation"}, "uom": "LF", "unit_cents": 6197, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["concrete", "footing", "pour"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CN-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CN-003", "scope_tag": "foundation", "label": "Slab on grade — 4 in w/ mesh", "kerf_division": {"code": "03", "label": "Concrete & Foundation"}, "uom": "SF", "unit_cents": 1794, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["slab", "grade", "mesh"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CN-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CN-004", "scope_tag": "foundation", "label": "Slab raise / infill", "kerf_division": {"code": "03", "label": "Concrete & Foundation"}, "uom": "SF", "unit_cents": 2609, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["slab", "raise", "infill"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CN-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CN-005", "scope_tag": "foundation", "label": "Stem wall / curb", "kerf_division": {"code": "03", "label": "Concrete & Foundation"}, "uom": "LF", "unit_cents": 8969, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["stem", "wall", "curb"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CN-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CN-006", "scope_tag": "foundation", "label": "Flatwork — patio/walk broom finish", "kerf_division": {"code": "03", "label": "Concrete & Foundation"}, "uom": "SF", "unit_cents": 2120, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["flatwork", "patio", "walk", "broom", "finish"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CN-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CN-007", "scope_tag": "foundation", "label": "Vapor barrier & base prep", "kerf_division": {"code": "03", "label": "Concrete & Foundation"}, "uom": "SF", "unit_cents": 245, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["vapor", "barrier", "base", "prep"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CN-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CN-008", "scope_tag": "foundation", "label": "Rebar/dowel into existing", "kerf_division": {"code": "03", "label": "Concrete & Foundation"}, "uom": "EA", "unit_cents": 2935, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["rebar", "dowel", "into"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CN-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CN-009", "scope_tag": "foundation", "label": "Moisture test / mitigation coat", "kerf_division": {"code": "03", "label": "Concrete & Foundation"}, "uom": "SF", "unit_cents": 367, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["moisture", "test", "mitigation", "coat"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CN-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-001", "scope_tag": "framing", "label": "Wall framing — new partition 2x4 @16", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "LF", "unit_cents": 18512, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["wall", "framing", "partition", "2x4"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-002", "scope_tag": "framing", "label": "Furring / shimming existing", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "LF", "unit_cents": 6657, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["furring", "shimming"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-003", "scope_tag": "framing", "label": "Header install — opening to 6 ft", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "EA", "unit_cents": 118652, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["header", "opening"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-004", "scope_tag": "framing", "label": "Beam install — LVL/steel w/ posts", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "EA", "unit_cents": 351458, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["beam", "lvl", "steel", "posts"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-005", "scope_tag": "framing", "label": "Pocket / archway reframe", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "EA", "unit_cents": 165748, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["pocket", "archway", "reframe"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-006", "scope_tag": "framing", "label": "Subfloor repair/replace", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "SF", "unit_cents": 1544, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["subfloor", "repair", "replace"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-007", "scope_tag": "framing", "label": "Ceiling joist sister/repair", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "EA", "unit_cents": 51988, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["ceiling", "joist", "sister", "repair"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-008", "scope_tag": "framing", "label": "Blocking/backing for cabinets & fixtures", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "LS", "unit_cents": 71458, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["blocking", "backing", "cabinets", "fixtures"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-009", "scope_tag": "framing", "label": "Decorative box/recess framing", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "EA", "unit_cents": 114489, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["decorative", "box", "recess", "framing"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-010", "scope_tag": "framing", "label": "Stair tread/riser repair", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "EA", "unit_cents": 30862, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["stair", "tread", "riser", "repair"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-010", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-011", "scope_tag": "framing", "label": "Exterior wall infill (opening delete)", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "EA", "unit_cents": 173902, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["exterior", "wall", "infill", "opening", "delete"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-011", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FR-012", "scope_tag": "framing", "label": "1-hr firewall — 5/8 Type X to code", "kerf_division": {"code": "06", "label": "Framing & Structural"}, "uom": "SF", "unit_cents": 1138, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["firewall", "type", "code"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FR-012", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-001", "scope_tag": "millwork", "label": "Baseboard — 5 in flat stock, supply+install", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "LF", "unit_cents": 1142, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["baseboard", "flat", "stock"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-001", "ricardo_included": true, "ricardo_quantity": 70.0, "ricardo_sell_total_cents": 79908, "ricardo_cost_total_cents": 51940},
  {"cost_code": "FC-002", "scope_tag": "millwork", "label": "Baseboard — premium profile", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "LF", "unit_cents": 1794, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["baseboard", "premium", "profile"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-003", "scope_tag": "millwork", "label": "Casing — door/window", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "LF", "unit_cents": 1305, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["casing", "door", "window"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-004", "scope_tag": "millwork", "label": "Crown molding — standard", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "LF", "unit_cents": 1957, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["crown", "molding", "standard"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-005", "scope_tag": "millwork", "label": "Modern flat trim / closure to ceiling", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "LF", "unit_cents": 2283, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["modern", "flat", "trim", "closure", "ceiling"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-005", "ricardo_included": true, "ricardo_quantity": 38.0, "ricardo_sell_total_cents": 86757, "ricardo_cost_total_cents": 56392},
  {"cost_code": "FC-006", "scope_tag": "millwork", "label": "Box beam — shop fabrication", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "LF", "unit_cents": 23646, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["box", "beam", "shop", "fabrication"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-007", "scope_tag": "millwork", "label": "Box beam — site install", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "LF", "unit_cents": 10356, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["box", "beam", "site"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-008", "scope_tag": "millwork", "label": "Wainscot/panel molding", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "SF", "unit_cents": 2283, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["wainscot", "panel", "molding"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-008", "ricardo_included": true, "ricardo_quantity": 60.0, "ricardo_sell_total_cents": 136985, "ricardo_cost_total_cents": 89040},
  {"cost_code": "FC-009", "scope_tag": "millwork", "label": "Floating shelves — supply & install", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "EA", "unit_cents": 35389, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["floating", "shelves"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-010", "scope_tag": "millwork", "label": "Interior door — slab swap", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "EA", "unit_cents": 47608, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["interior", "door", "slab", "swap"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-010", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-011", "scope_tag": "millwork", "label": "Interior door — new prehung", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "EA", "unit_cents": 80125, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["interior", "door", "prehung"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-011", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-012", "scope_tag": "millwork", "label": "Door hardware", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "EA", "unit_cents": 16685, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["door", "hardware"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-012", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-013", "scope_tag": "millwork", "label": "Closet build-out", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "LF", "unit_cents": 24789, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["closet", "build", "out"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-013", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FC-014", "scope_tag": "millwork", "label": "Window sill/stool & apron", "kerf_division": {"code": "06b", "label": "Finish Carpentry & Millwork"}, "uom": "EA", "unit_cents": 28038, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["window", "sill", "stool", "apron"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FC-014", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CB-001", "scope_tag": "cabinetry", "label": "Custom cabinetry — base, material+fab", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 106000, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["custom", "cabinetry", "base", "fab"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-001", "ricardo_included": true, "ricardo_quantity": 35.0, "ricardo_sell_total_cents": 3710000, "ricardo_cost_total_cents": 2411500},
  {"cost_code": "CB-002", "scope_tag": "cabinetry", "label": "Custom cabinetry — uppers, material+fab", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 84800, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["custom", "cabinetry", "uppers", "fab"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-002", "ricardo_included": true, "ricardo_quantity": 30.0, "ricardo_sell_total_cents": 2544000, "ricardo_cost_total_cents": 1653600},
  {"cost_code": "CB-003", "scope_tag": "cabinetry", "label": "Custom cabinetry — tall/pantry, material+fab", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 146769, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["custom", "cabinetry", "tall", "pantry", "fab"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-003", "ricardo_included": true, "ricardo_quantity": 8.0, "ricardo_sell_total_cents": 1174154, "ricardo_cost_total_cents": 763200},
  {"cost_code": "CB-004", "scope_tag": "cabinetry", "label": "Semi-custom line — installed-equivalent", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 65231, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["semi", "custom", "line", "installed", "equivalent"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CB-005", "scope_tag": "cabinetry", "label": "Reface — doors/fronts/ends on existing boxes", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 100292, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["reface", "doors", "fronts", "ends", "boxes"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CB-006", "scope_tag": "cabinetry", "label": "Slab door/front upcharge — premium veneer", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 14677, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["slab", "door", "front", "upcharge", "premium", "veneer"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-006", "ricardo_included": true, "ricardo_quantity": 73.0, "ricardo_sell_total_cents": 1071415, "ricardo_cost_total_cents": 696420},
  {"cost_code": "CB-007", "scope_tag": "cabinetry", "label": "Hardwax-oil finish (e.g., Rubio class)", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 8969, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["hardwax", "oil", "finish", "rubio"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-007", "ricardo_included": true, "ricardo_quantity": 73.0, "ricardo_sell_total_cents": 654754, "ricardo_cost_total_cents": 425590},
  {"cost_code": "CB-008", "scope_tag": "cabinetry", "label": "Uppers raised to ceiling + closure", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 13862, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["uppers", "raised", "ceiling", "closure"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-008", "ricardo_included": true, "ricardo_quantity": 38.0, "ricardo_sell_total_cents": 526738, "ricardo_cost_total_cents": 342380},
  {"cost_code": "CB-009", "scope_tag": "cabinetry", "label": "Island add-on — back-side cabinets", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 65231, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["island", "add", "back", "side", "cabinets"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CB-010", "scope_tag": "cabinetry", "label": "Hardware — soft-close pkg", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "EA", "unit_cents": 4566, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["hardware", "soft", "close", "pkg"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-010", "ricardo_included": true, "ricardo_quantity": 55.0, "ricardo_sell_total_cents": 251138, "ricardo_cost_total_cents": 163240},
  {"cost_code": "CB-011", "scope_tag": "cabinetry", "label": "Spice pullout insert", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "EA", "unit_cents": 62785, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["spice", "pullout", "insert"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-011", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CB-012", "scope_tag": "cabinetry", "label": "Corner lazy Susan / blind-corner unit", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "EA", "unit_cents": 69308, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["corner", "lazy", "susan", "blind", "unit"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-012", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CB-013", "scope_tag": "cabinetry", "label": "Toe-kick LED provision in cabinetry", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "EA", "unit_cents": 22015, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["toe", "kick", "led", "provision", "cabinetry"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-013", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CB-014", "scope_tag": "cabinetry", "label": "Vanity — supplied unit ALLOWANCE", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "EA", "unit_cents": 195692, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["vanity", "unit"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-014", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 195692, "ricardo_cost_total_cents": 127200},
  {"cost_code": "CB-015", "scope_tag": "cabinetry", "label": "Delivery to site", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "EA", "unit_cents": 48923, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["delivery", "site"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-015", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 48923, "ricardo_cost_total_cents": 31800},
  {"cost_code": "CB-016", "scope_tag": "cabinetry", "label": "Install — set/level/scribe", "kerf_division": {"code": "12", "label": "Cabinetry"}, "uom": "LF", "unit_cents": 16550, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["set", "level", "scribe"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CB-016", "ricardo_included": true, "ricardo_quantity": 73.0, "ricardo_sell_total_cents": 1188350, "ricardo_cost_total_cents": 772428},
  {"cost_code": "CT-001", "scope_tag": "countertops", "label": "Quartz — material", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "SF", "unit_cents": 8969, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["quartz"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-001", "ricardo_included": true, "ricardo_quantity": 12.0, "ricardo_sell_total_cents": 107631, "ricardo_cost_total_cents": 69960},
  {"cost_code": "CT-002", "scope_tag": "countertops", "label": "Quartzite — material", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "SF", "unit_cents": 12231, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["quartzite"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-002", "ricardo_included": true, "ricardo_quantity": 130.0, "ricardo_sell_total_cents": 1590000, "ricardo_cost_total_cents": 1033500},
  {"cost_code": "CT-003", "scope_tag": "countertops", "label": "Honed finish upcharge", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "SF", "unit_cents": 2446, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["honed", "finish", "upcharge"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-003", "ricardo_included": true, "ricardo_quantity": 130.0, "ricardo_sell_total_cents": 318000, "ricardo_cost_total_cents": 206700},
  {"cost_code": "CT-004", "scope_tag": "countertops", "label": "Fabrication", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "SF", "unit_cents": 4892, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["fabrication"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-004", "ricardo_included": true, "ricardo_quantity": 123.0, "ricardo_sell_total_cents": 601754, "ricardo_cost_total_cents": 391140},
  {"cost_code": "CT-005", "scope_tag": "countertops", "label": "Install & seam", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "SF", "unit_cents": 2762, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["seam"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-005", "ricardo_included": true, "ricardo_quantity": 78.0, "ricardo_sell_total_cents": 211944, "ricardo_cost_total_cents": 137764},
  {"cost_code": "CT-006", "scope_tag": "countertops", "label": "Template & coordination", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "LS", "unit_cents": 102222, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["template", "coordination"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-006", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 100412, "ricardo_cost_total_cents": 65268},
  {"cost_code": "CT-007", "scope_tag": "countertops", "label": "Full-height splash — vertical INSTALL premium only", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "SF", "unit_cents": 3588, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["full", "height", "splash", "vertical", "install"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-007"},
  {"cost_code": "CT-008", "scope_tag": "countertops", "label": "4 in splash", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "LF", "unit_cents": 2935, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["splash"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CT-009", "scope_tag": "countertops", "label": "Edge upgrade (mitered/built-up)", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "LF", "unit_cents": 6197, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["edge", "upgrade", "mitered", "built"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "CT-010", "scope_tag": "countertops", "label": "Sink/cooktop cutout", "kerf_division": {"code": "12b", "label": "Countertops & Stone"}, "uom": "EA", "unit_cents": 20385, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["sink", "cooktop", "cutout"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/CT-010", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DW-001", "scope_tag": "windows_doors", "label": "Window — retrofit vinyl, supply+install", "kerf_division": {"code": "08", "label": "Doors & Windows"}, "uom": "EA", "unit_cents": 71557, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["window", "retrofit", "vinyl"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DW-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DW-002", "scope_tag": "windows_doors", "label": "Window — new-construction w/ flash+patch", "kerf_division": {"code": "08", "label": "Doors & Windows"}, "uom": "EA", "unit_cents": 175606, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["window", "construction", "flash", "patch"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DW-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DW-003", "scope_tag": "windows_doors", "label": "Patio slider — retrofit", "kerf_division": {"code": "08", "label": "Doors & Windows"}, "uom": "EA", "unit_cents": 183883, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["patio", "slider", "retrofit"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DW-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DW-004", "scope_tag": "windows_doors", "label": "French doors — supply+install", "kerf_division": {"code": "08", "label": "Doors & Windows"}, "uom": "EA", "unit_cents": 875009, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["french", "doors"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DW-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DW-005", "scope_tag": "windows_doors", "label": "Entry door — prehung exterior", "kerf_division": {"code": "08", "label": "Doors & Windows"}, "uom": "EA", "unit_cents": 169280, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["entry", "door", "prehung", "exterior"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DW-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DW-006", "scope_tag": "windows_doors", "label": "Pocketing/folding glass wall", "kerf_division": {"code": "08", "label": "Doors & Windows"}, "uom": "LF", "unit_cents": 234634, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["pocketing", "folding", "glass", "wall"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DW-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DW-007", "scope_tag": "windows_doors", "label": "Skylight — new incl roof tie-in", "kerf_division": {"code": "08", "label": "Doors & Windows"}, "uom": "EA", "unit_cents": 248991, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["skylight", "incl", "roof", "tie"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DW-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DR-001", "scope_tag": "drywall", "label": "Hang & finish — new walls L4", "kerf_division": {"code": "09a", "label": "Drywall & Plaster"}, "uom": "SF", "unit_cents": 530, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["hang", "finish", "walls"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DR-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DR-002", "scope_tag": "drywall", "label": "Patch & repair — per location", "kerf_division": {"code": "09a", "label": "Drywall & Plaster"}, "uom": "EA", "unit_cents": 32078, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["patch", "repair", "location"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DR-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DR-003", "scope_tag": "drywall", "label": "Level 5 smooth-wall finish", "kerf_division": {"code": "09a", "label": "Drywall & Plaster"}, "uom": "SF", "unit_cents": 391, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["level", "smooth", "wall", "finish"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DR-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DR-004", "scope_tag": "drywall", "label": "Skim coat existing — full wall", "kerf_division": {"code": "09a", "label": "Drywall & Plaster"}, "uom": "SF", "unit_cents": 342, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["skim", "coat", "full", "wall"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DR-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DR-005", "scope_tag": "drywall", "label": "Texture match", "kerf_division": {"code": "09a", "label": "Drywall & Plaster"}, "uom": "SF", "unit_cents": 228, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["texture", "match"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DR-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DR-006", "scope_tag": "drywall", "label": "Ceiling repair after recan/HVAC", "kerf_division": {"code": "09a", "label": "Drywall & Plaster"}, "uom": "EA", "unit_cents": 41425, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["ceiling", "repair", "after", "recan", "hvac"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DR-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "DR-007", "scope_tag": "drywall", "label": "Acoustic ceiling removal & refinish", "kerf_division": {"code": "09a", "label": "Drywall & Plaster"}, "uom": "SF", "unit_cents": 734, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["acoustic", "ceiling", "removal", "refinish"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/DR-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "TL-001", "scope_tag": "tile", "label": "Tile install — standard format, floor", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "SF", "unit_cents": 1305, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["tile", "standard", "format", "floor"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "TL-002", "scope_tag": "tile", "label": "Tile install — LARGE FORMAT (24in+), floor", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "SF", "unit_cents": 1794, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["tile", "large", "format", "24in", "floor"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-002", "ricardo_included": true, "ricardo_quantity": 250.0, "ricardo_sell_total_cents": 448462, "ricardo_cost_total_cents": 291500},
  {"cost_code": "TL-003", "scope_tag": "tile", "label": "Tile — MATERIAL allowance", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "SF", "unit_cents": 978, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["tile", "material", "allowance"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-003"},
  {"cost_code": "TL-004", "scope_tag": "tile", "label": "Tile install — wall/splash", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "SF", "unit_cents": 1957, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["tile", "wall", "splash"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "TL-005", "scope_tag": "tile", "label": "Substrate prep / self-leveler", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "SF", "unit_cents": 367, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["substrate", "prep", "self", "leveler"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-005", "ricardo_included": true, "ricardo_quantity": 250.0, "ricardo_sell_total_cents": 91731, "ricardo_cost_total_cents": 59625},
  {"cost_code": "TL-006", "scope_tag": "tile", "label": "Shower pan — hot mop or equal", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "EA", "unit_cents": 81538, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["shower", "pan", "hot", "mop", "equal"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "TL-007", "scope_tag": "tile", "label": "Shower waterproof — board/liquid system", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "EA", "unit_cents": 138615, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["shower", "waterproof", "board", "liquid", "system"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "TL-008", "scope_tag": "tile", "label": "Curb & bench build", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "EA", "unit_cents": 75572, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["curb", "bench", "build"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "TL-009", "scope_tag": "tile", "label": "Niche build & waterproof", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "EA", "unit_cents": 46317, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["niche", "build", "waterproof"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "TL-010", "scope_tag": "tile", "label": "Tile repair — small patch", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "LS", "unit_cents": 79588, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["tile", "repair", "small", "patch"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-010", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "TL-011", "scope_tag": "tile", "label": "Grout/caulk refresh", "kerf_division": {"code": "09b", "label": "Tile"}, "uom": "LS", "unit_cents": 58462, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["grout", "caulk", "refresh"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/TL-011", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FL-001", "scope_tag": "flooring", "label": "Engineered wood — material ALLOWANCE", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "SF", "unit_cents": 897, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["engineered", "wood"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-001", "ricardo_included": true, "ricardo_quantity": 250.0, "ricardo_sell_total_cents": 326154, "ricardo_cost_total_cents": 212000},
  {"cost_code": "FL-002", "scope_tag": "flooring", "label": "Engineered glue-down — install", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "SF", "unit_cents": 571, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["engineered", "glue", "down"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FL-003", "scope_tag": "flooring", "label": "Engineered float/click — install", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "SF", "unit_cents": 489, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["engineered", "float", "click"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FL-004", "scope_tag": "flooring", "label": "Hardwood sand & refinish", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "SF", "unit_cents": 815, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["hardwood", "sand", "refinish"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FL-005", "scope_tag": "flooring", "label": "Hardwax-oil floor finish system", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "SF", "unit_cents": 978, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["hardwax", "oil", "floor", "finish", "system"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FL-006", "scope_tag": "flooring", "label": "LVP — supply & install", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "SF", "unit_cents": 1223, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["lvp"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FL-007", "scope_tag": "flooring", "label": "Carpet — supply & install", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "SY", "unit_cents": 8969, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["carpet"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FL-008", "scope_tag": "flooring", "label": "Floor prep / leveling / moisture", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "SF", "unit_cents": 196, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["floor", "prep", "leveling", "moisture"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FL-009", "scope_tag": "flooring", "label": "Transitions & reducers", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "EA", "unit_cents": 10162, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["transitions", "reducers"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "FL-010", "scope_tag": "flooring", "label": "Stair — retread hardwood", "kerf_division": {"code": "09c", "label": "Flooring"}, "uom": "EA", "unit_cents": 53217, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["stair", "retread", "hardwood"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/FL-010", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PT-001", "scope_tag": "paint", "label": "Interior — walls only, per room", "kerf_division": {"code": "09d", "label": "Paint"}, "uom": "EA", "unit_cents": 73385, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["interior", "walls", "room"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PT-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PT-002", "scope_tag": "paint", "label": "Interior — walls+ceiling+trim, per room", "kerf_division": {"code": "09d", "label": "Paint"}, "uom": "EA", "unit_cents": 122308, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["interior", "walls", "ceiling", "trim", "room"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PT-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PT-003", "scope_tag": "paint", "label": "Interior repaint — by floor area", "kerf_division": {"code": "09d", "label": "Paint"}, "uom": "SF", "unit_cents": 506, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["interior", "repaint", "floor", "area"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PT-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PT-004", "scope_tag": "paint", "label": "Walls+ceiling — by wall/ceiling SF", "kerf_division": {"code": "09d", "label": "Paint"}, "uom": "SF", "unit_cents": 261, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["walls", "ceiling", "wall"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PT-004", "ricardo_included": true, "ricardo_quantity": 700.0, "ricardo_sell_total_cents": 182646, "ricardo_cost_total_cents": 118720},
  {"cost_code": "PT-005", "scope_tag": "paint", "label": "Baseboard/trim paint", "kerf_division": {"code": "09d", "label": "Paint"}, "uom": "LF", "unit_cents": 408, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["baseboard", "trim", "paint"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PT-005", "ricardo_included": true, "ricardo_quantity": 70.0, "ricardo_sell_total_cents": 28538, "ricardo_cost_total_cents": 18550},
  {"cost_code": "PT-006", "scope_tag": "paint", "label": "Cabinet paint — spray finish", "kerf_division": {"code": "09d", "label": "Paint"}, "uom": "LF", "unit_cents": 15492, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["cabinet", "paint", "spray", "finish"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PT-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PT-007", "scope_tag": "paint", "label": "Exterior body & trim", "kerf_division": {"code": "09d", "label": "Paint"}, "uom": "SF", "unit_cents": 554, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["exterior", "body", "trim"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PT-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PT-008", "scope_tag": "paint", "label": "Specialty stain/seal — wood walls", "kerf_division": {"code": "09d", "label": "Paint"}, "uom": "SF", "unit_cents": 1794, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["specialty", "stain", "seal", "wood", "walls"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PT-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PT-009", "scope_tag": "paint", "label": "Accent/feature piece", "kerf_division": {"code": "09d", "label": "Paint"}, "uom": "EA", "unit_cents": 41425, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["accent", "feature", "piece"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PT-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "SP-001", "scope_tag": "millwork", "label": "Mirror install — owner supplied", "kerf_division": {"code": "10", "label": "Specialties & Accessories"}, "uom": "EA", "unit_cents": 19897, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["mirror"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SP-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "SP-002", "scope_tag": "millwork", "label": "Bath accessories set", "kerf_division": {"code": "10", "label": "Specialties & Accessories"}, "uom": "EA", "unit_cents": 30862, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["bath", "accessories", "set"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SP-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "SP-003", "scope_tag": "millwork", "label": "Shower glass — frameless, supply+install", "kerf_division": {"code": "10", "label": "Specialties & Accessories"}, "uom": "EA", "unit_cents": 301692, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["shower", "glass", "frameless"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SP-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "SP-004", "scope_tag": "millwork", "label": "Wallpaper installation", "kerf_division": {"code": "10", "label": "Specialties & Accessories"}, "uom": "SF", "unit_cents": 734, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["wallpaper", "installation"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SP-004", "ricardo_included": true, "ricardo_quantity": 60.0, "ricardo_sell_total_cents": 44031, "ricardo_cost_total_cents": 28620},
  {"cost_code": "SP-005", "scope_tag": "millwork", "label": "Wallpaper material ALLOWANCE", "kerf_division": {"code": "10", "label": "Specialties & Accessories"}, "uom": "SF", "unit_cents": 652, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["wallpaper"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SP-005", "ricardo_included": true, "ricardo_quantity": 60.0, "ricardo_sell_total_cents": 39138, "ricardo_cost_total_cents": 25440},
  {"cost_code": "SP-006", "scope_tag": "millwork", "label": "Closet system — wire", "kerf_division": {"code": "10", "label": "Specialties & Accessories"}, "uom": "LF", "unit_cents": 10845, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["closet", "system", "wire"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SP-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "SP-007", "scope_tag": "millwork", "label": "Closet system — melamine/custom", "kerf_division": {"code": "10", "label": "Specialties & Accessories"}, "uom": "LF", "unit_cents": 22015, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["closet", "system", "melamine", "custom"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SP-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "SP-008", "scope_tag": "millwork", "label": "Fireplace facing modernization", "kerf_division": {"code": "10", "label": "Specialties & Accessories"}, "uom": "LS", "unit_cents": 478018, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["fireplace", "facing", "modernization"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SP-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "SP-009", "scope_tag": "millwork", "label": "TV mount / AV bracket", "kerf_division": {"code": "10", "label": "Specialties & Accessories"}, "uom": "EA", "unit_cents": 21528, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["mount", "bracket"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SP-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "AP-001", "scope_tag": "appliances", "label": "Appliance R&R — save & reinstall pkg (6 pc)", "kerf_division": {"code": "11", "label": "Appliances & Equipment"}, "uom": "LS", "unit_cents": 165502, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["appliance", "save", "reinstall", "pkg"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/AP-001", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 162788, "ricardo_cost_total_cents": 105812},
  {"cost_code": "AP-002", "scope_tag": "appliances", "label": "Appliance install — new, per unit", "kerf_division": {"code": "11", "label": "Appliances & Equipment"}, "uom": "EA", "unit_cents": 30448, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["appliance", "unit"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/AP-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "AP-003", "scope_tag": "appliances", "label": "Hood install — ducted, minor duct", "kerf_division": {"code": "11", "label": "Appliances & Equipment"}, "uom": "EA", "unit_cents": 70680, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["hood", "ducted", "minor", "duct"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/AP-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "AP-004", "scope_tag": "appliances", "label": "Gas appliance set & leak test", "kerf_division": {"code": "11", "label": "Appliances & Equipment"}, "uom": "EA", "unit_cents": 41425, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["gas", "appliance", "set", "leak", "test"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/AP-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "AP-005", "scope_tag": "appliances", "label": "Built-in panel/anti-tip hardware", "kerf_division": {"code": "11", "label": "Appliances & Equipment"}, "uom": "EA", "unit_cents": 56855, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["built", "panel", "anti", "tip", "hardware"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/AP-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PL-001", "scope_tag": "plumbing", "label": "Fixture disconnect/reconnect", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 37508, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["fixture", "disconnect", "reconnect"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-001", "ricardo_included": true, "ricardo_quantity": 2.0, "ricardo_sell_total_cents": 75015, "ricardo_cost_total_cents": 48760},
  {"cost_code": "PL-002", "scope_tag": "plumbing", "label": "Faucet/sink install — owner supplied", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 30169, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["faucet", "sink"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-002", "ricardo_included": true, "ricardo_quantity": 2.0, "ricardo_sell_total_cents": 60338, "ricardo_cost_total_cents": 39220},
  {"cost_code": "PL-003", "scope_tag": "plumbing", "label": "Toilet — install new", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 36692, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["toilet"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-003", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 36692, "ricardo_cost_total_cents": 23850},
  {"cost_code": "PL-004", "scope_tag": "plumbing", "label": "Toilet — unit ALLOWANCE", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 73385, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["toilet", "unit"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-004", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 73385, "ricardo_cost_total_cents": 47700},
  {"cost_code": "PL-005", "scope_tag": "plumbing", "label": "Shower valve replace (incl access)", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 106000, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["shower", "valve", "replace", "incl", "access"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PL-006", "scope_tag": "plumbing", "label": "Tub set — alcove", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 138615, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["tub", "set", "alcove"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PL-007", "scope_tag": "plumbing", "label": "Disposal install", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 26908, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["disposal"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PL-008", "scope_tag": "plumbing", "label": "Dishwasher hookup", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 24462, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["dishwasher", "hookup"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-008", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 24462, "ricardo_cost_total_cents": 15900},
  {"cost_code": "PL-009", "scope_tag": "plumbing", "label": "Gas line — run/extend per appliance", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 122308, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["gas", "line", "run", "extend", "appliance"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PL-010", "scope_tag": "plumbing", "label": "Water line relocation — per point", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 69308, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["water", "line", "relocation", "point"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-010", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PL-011", "scope_tag": "plumbing", "label": "Drain relocation — per point", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 93769, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["drain", "relocation", "point"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-011", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PL-012", "scope_tag": "plumbing", "label": "Sewer lateral replace", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "LF", "unit_cents": 45662, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["sewer", "lateral", "replace"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-012", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PL-013", "scope_tag": "plumbing", "label": "Water heater — tank swap", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 301692, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["water", "heater", "tank", "swap"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-013", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "PL-014", "scope_tag": "plumbing", "label": "Tankless conversion", "kerf_division": {"code": "22", "label": "Plumbing"}, "uom": "EA", "unit_cents": 684923, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["tankless", "conversion"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/PL-014", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "HV-001", "scope_tag": "hvac", "label": "System changeout — condenser+coil+furnace", "kerf_division": {"code": "23", "label": "HVAC"}, "uom": "LS", "unit_cents": 2038462, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["system", "changeout", "condenser", "coil", "furnace"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/HV-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "HV-002", "scope_tag": "hvac", "label": "Heat pump conversion", "kerf_division": {"code": "23", "label": "HVAC"}, "uom": "LS", "unit_cents": 2527692, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["heat", "pump", "conversion"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/HV-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "HV-003", "scope_tag": "hvac", "label": "Ductwork — replace per run", "kerf_division": {"code": "23", "label": "HVAC"}, "uom": "EA", "unit_cents": 73385, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["ductwork", "replace", "run"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/HV-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "HV-004", "scope_tag": "hvac", "label": "Full duct replacement (typ home)", "kerf_division": {"code": "23", "label": "HVAC"}, "uom": "LS", "unit_cents": 782769, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["full", "duct", "replacement", "home"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/HV-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "HV-005", "scope_tag": "hvac", "label": "Register/grille swap", "kerf_division": {"code": "23", "label": "HVAC"}, "uom": "EA", "unit_cents": 13423, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["register", "grille", "swap"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/HV-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "HV-006", "scope_tag": "hvac", "label": "Mini-split — single zone", "kerf_division": {"code": "23", "label": "HVAC"}, "uom": "EA", "unit_cents": 684923, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["mini", "split", "single", "zone"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/HV-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "HV-007", "scope_tag": "hvac", "label": "Bath exhaust fan — new/upgrade", "kerf_division": {"code": "23", "label": "HVAC"}, "uom": "EA", "unit_cents": 60994, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["bath", "exhaust", "fan", "upgrade"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/HV-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "HV-008", "scope_tag": "hvac", "label": "Kitchen hood duct — new run", "kerf_division": {"code": "23", "label": "HVAC"}, "uom": "LS", "unit_cents": 120357, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["kitchen", "hood", "duct", "run"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/HV-008", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "HV-009", "scope_tag": "hvac", "label": "Smart thermostat", "kerf_division": {"code": "23", "label": "HVAC"}, "uom": "EA", "unit_cents": 48046, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["smart", "thermostat"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/HV-009", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EL-001", "scope_tag": "electrical", "label": "Panel upgrade — 200A", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 619692, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["panel", "upgrade", "200a"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EL-002", "scope_tag": "electrical", "label": "Subpanel add", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 260923, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["subpanel", "add"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EL-003", "scope_tag": "electrical", "label": "New dedicated circuit", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 69308, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["dedicated", "circuit"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EL-004", "scope_tag": "electrical", "label": "Recessed can — new, per light", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 37508, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["recessed", "can", "light"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-004", "ricardo_included": true, "ricardo_quantity": 8.0, "ricardo_sell_total_cents": 300062, "ricardo_cost_total_cents": 195040},
  {"cost_code": "EL-005", "scope_tag": "electrical", "label": "Fixture install — owner supplied", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 53815, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["fixture"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-005", "ricardo_included": true, "ricardo_quantity": 2.0, "ricardo_sell_total_cents": 107631, "ricardo_cost_total_cents": 69960},
  {"cost_code": "EL-006", "scope_tag": "electrical", "label": "Sconce install — owner supplied", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 55446, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["sconce"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EL-007", "scope_tag": "electrical", "label": "Switch/outlet — replace/add", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 15492, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["switch", "outlet", "replace", "add"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EL-008", "scope_tag": "electrical", "label": "Dimmer / smart switch", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 22831, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["dimmer", "smart", "switch"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-008", "ricardo_included": true, "ricardo_quantity": 2.0, "ricardo_sell_total_cents": 45662, "ricardo_cost_total_cents": 29680},
  {"cost_code": "EL-009", "scope_tag": "electrical", "label": "Under-cabinet LED — hardwired, per LF", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "LF", "unit_cents": 6849, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["under", "cabinet", "led", "hardwired"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-009", "ricardo_included": true, "ricardo_quantity": 30.0, "ricardo_sell_total_cents": 205477, "ricardo_cost_total_cents": 133560},
  {"cost_code": "EL-010", "scope_tag": "electrical", "label": "Toe-kick LED — per LF", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "LF", "unit_cents": 4566, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["toe", "kick", "led"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-010", "ricardo_included": true, "ricardo_quantity": 35.0, "ricardo_sell_total_cents": 159815, "ricardo_cost_total_cents": 103880},
  {"cost_code": "EL-011", "scope_tag": "electrical", "label": "LED lighting circuit + driver + switch", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "LS", "unit_cents": 106000, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["led", "lighting", "circuit", "driver", "switch"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-011", "ricardo_included": true, "ricardo_quantity": 1.0, "ricardo_sell_total_cents": 106000, "ricardo_cost_total_cents": 68900},
  {"cost_code": "EL-012", "scope_tag": "electrical", "label": "EV charger circuit", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 203846, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["charger", "circuit"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-012", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EL-013", "scope_tag": "electrical", "label": "Smoke/CO to code", "kerf_division": {"code": "26", "label": "Electrical"}, "uom": "EA", "unit_cents": 15054, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["smoke", "code"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EL-013", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EX-001", "scope_tag": "exterior", "label": "Stucco patch & color coat", "kerf_division": {"code": "31", "label": "Exterior & Site"}, "uom": "SF", "unit_cents": 2283, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["stucco", "patch", "color", "coat"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EX-001", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EX-002", "scope_tag": "exterior", "label": "Siding repair/replace", "kerf_division": {"code": "31", "label": "Exterior & Site"}, "uom": "SF", "unit_cents": 1957, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["siding", "repair", "replace"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EX-002", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EX-003", "scope_tag": "exterior", "label": "Exterior window rehab ALLOWANCE", "kerf_division": {"code": "31", "label": "Exterior & Site"}, "uom": "LS", "unit_cents": 407692, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["exterior", "window", "rehab"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EX-003", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EX-004", "scope_tag": "exterior", "label": "Deck — framing & decking", "kerf_division": {"code": "31", "label": "Exterior & Site"}, "uom": "SF", "unit_cents": 8969, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["deck", "framing", "decking"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EX-004", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EX-005", "scope_tag": "exterior", "label": "Structure removal (pergola/shed)", "kerf_division": {"code": "31", "label": "Exterior & Site"}, "uom": "LS", "unit_cents": 102345, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["structure", "removal", "pergola", "shed"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EX-005", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EX-006", "scope_tag": "exterior", "label": "Fence — wood per LF", "kerf_division": {"code": "31", "label": "Exterior & Site"}, "uom": "LF", "unit_cents": 13862, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["fence", "wood"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EX-006", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "EX-007", "scope_tag": "exterior", "label": "Drainage — area drain per point", "kerf_division": {"code": "31", "label": "Exterior & Site"}, "uom": "EA", "unit_cents": 69308, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["drainage", "area", "drain", "point"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/EX-007", "ricardo_included": false, "ricardo_quantity": null, "ricardo_sell_total_cents": 0, "ricardo_cost_total_cents": 0},
  {"cost_code": "SB-001", "scope_tag": "millwork", "label": "Specialty cabinetry/millwork shop — pass-through", "kerf_division": {"code": "XX", "label": "Subs & Pass-Throughs"}, "uom": "LS", "unit_cents": 0, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["specialty", "cabinetry", "millwork", "shop", "pass"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SB-001"},
  {"cost_code": "SB-002", "scope_tag": "millwork", "label": "Designer-supplied materials — excluded", "kerf_division": {"code": "XX", "label": "Subs & Pass-Throughs"}, "uom": "LS", "unit_cents": 0, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["designer", "supplied", "materials", "excluded"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SB-002"},
  {"cost_code": "SB-003", "scope_tag": "millwork", "label": "Specialty sub — quote-based", "kerf_division": {"code": "XX", "label": "Subs & Pass-Throughs"}, "uom": "LS", "unit_cents": 0, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["specialty", "quote", "based"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SB-003"},
  {"cost_code": "SB-004", "scope_tag": "millwork", "label": "Engineering — pass-through", "kerf_division": {"code": "XX", "label": "Subs & Pass-Throughs"}, "uom": "LS", "unit_cents": 0, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["engineering", "pass", "through"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SB-004"},
  {"cost_code": "SB-005", "scope_tag": "millwork", "label": "Permit fees — pass-through at cost", "kerf_division": {"code": "XX", "label": "Subs & Pass-Throughs"}, "uom": "LS", "unit_cents": 0, "source_layer": "KERF_SEED", "review_required": true, "keywords": ["permit", "fees", "pass", "through", "cost"], "source_ref": "kerf://kerf-seed/rate-card/workbook-v2_1/SB-005"},
];

// ── Kerf division registry (derived from the founder seed; the canonical GGR-19 codes) ──
const KERF_DIVISION_BY_CODE: ReadonlyMap<string, KerfDivision> = (() => {
  const byCode = new Map<string, KerfDivision>();
  for (const line of RICARDO_FILLED_RATE_CARD) {
    if (!byCode.has(line.kerf_division.code)) byCode.set(line.kerf_division.code, line.kerf_division);
  }
  return byCode;
})();

/** Canonical Kerf division for a code (accepts letter-suffixed GGR codes like 06b, 09a-09d, 12b). */
export function kerfDivisionForCode(code: string): KerfDivision | null {
  return KERF_DIVISION_BY_CODE.get(code.trim().toLowerCase()) ?? KERF_DIVISION_BY_CODE.get(code.trim()) ?? null;
}

export function tenantRateCardFor(tenantId: string): readonly TenantRateCardLine[] { return tenantId === 'tenant_ggr' ? RICARDO_FILLED_RATE_CARD : []; }
export function isTenantRateCardSourceRef(sourceRef: string | null | undefined): boolean { return typeof sourceRef === 'string' && sourceRef.startsWith('kerf://kerf-seed/rate-card/'); }
export function ricardoFilledIncludedRows(rateCard: readonly TenantRateCardLine[] = RICARDO_FILLED_RATE_CARD): readonly TenantRateCardLine[] { return rateCard.filter((line) => line.ricardo_included === true); }
export type RateCardMatchKind = 'line_id' | 'keyword';

export interface RateCardMatchDetail {
  readonly line: TenantRateCardLine;
  readonly matched_by: RateCardMatchKind;
}

/** Like matchTenantRateCardLine, but reports WHICH path matched — the telemetry
 * that keeps the keyword fallback measurable (polish card Part A). */
export function matchTenantRateCardLineDetailed(input: RateCardMatchInput): RateCardMatchDetail | null {
  const rates = input.rateCard ?? tenantRateCardFor(input.tenantId);
  const exactId = normalizeId(input.lineId);
  if (exactId) {
    const exact = rates.find((line) => normalizeId(line.cost_code) === exactId);
    if (exact) return { line: exact, matched_by: 'line_id' };
  }
  const normalizedUom = normalizeToken(input.uom);
  const description = normalizeText(input.description);
  const scoped = rates.filter((line) => line.scope_tag === input.scopeTag && normalizeToken(line.uom) === normalizedUom);
  if (scoped.length === 0) return null;
  let best: { line: TenantRateCardLine; score: number } | null = null;
  for (const line of scoped) {
    const score = scoreKeywords(description, line.keywords);
    if (score <= 0) continue;
    if (best === null || score > best.score) best = { line, score };
  }
  return best ? { line: best.line, matched_by: 'keyword' } : null;
}

export function matchTenantRateCardLine(input: RateCardMatchInput): TenantRateCardLine | null {
  return matchTenantRateCardLineDetailed(input)?.line ?? null;
}

function scoreKeywords(description: string, keywords: readonly string[]): number {
  let score = 0;
  const descriptionTokens = new Set(description.split(' ').filter(Boolean));
  for (const keyword of keywords) {
    const normalized = normalizeText(keyword);
    if (!normalized) continue;
    if (description.includes(normalized)) {
      score += normalized.split(' ').length;
      continue;
    }
    const tokenHit = normalized
      .split(' ')
      .some((token) => descriptionTokens.has(token) || descriptionTokens.has(singularize(token)) || descriptionTokens.has(`${token}s`));
    if (tokenHit) score += 1;
  }
  return score;
}
function normalizeToken(value: string): string { return value.trim().toUpperCase(); }
function normalizeId(value: string | null | undefined): string { return typeof value === 'string' ? value.trim().toUpperCase() : ''; }
function normalizeText(value: string): string { return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').replace(/\s+/g, ' ').trim(); }
function singularize(value: string): string { return value.endsWith('s') && value.length > 3 ? value.slice(0, -1) : value; }
