export type WireframeSpineStatus =
  | 'canon_wired'
  | 'mapped_pending_rebuild'
  | 'stub_or_holding'
  | 'redirect'
  | 'client_surface'
  | 'missing_canon_face'
  | 'future_or_unrouted';

export interface WireframeTransition {
  readonly trigger: string;
  readonly route: string;
  readonly face: string;
  readonly note?: string;
}

export interface WireframeSpineEntry {
  readonly route: string;
  readonly appFile?: string;
  readonly domain: string;
  readonly surface: string;
  readonly wireframes: readonly string[];
  readonly status: WireframeSpineStatus;
  readonly notes: string;
  readonly next: readonly WireframeTransition[];
}

export interface WireframeReferenceEntry {
  readonly wireframe: string;
  readonly intendedSurface: string;
  readonly intendedRoute: string;
  readonly status: WireframeSpineStatus;
  readonly notes: string;
}

const homeTabs: readonly WireframeTransition[] = [
  { trigger: 'Bottom Home', route: '/', face: 'F-A1_mobile_owner_home.html' },
  { trigger: 'Bottom Start', route: '/create', face: 'F-S1_mobile_start_action_sheet.html' },
  { trigger: 'Bottom Speak', route: '/right-hand', face: 'F-RH1_mobile_right_hand_voice_overlay.html' },
  { trigger: 'Bottom Camera', route: '/camera', face: 'F-CAM1_mobile_camera.html' },
  { trigger: 'Bottom More', route: '/more', face: 'F-D1_mobile_more_sidebar.html' },
];

export const WIREFRAME_SPINE_MAP: readonly WireframeSpineEntry[] = [
  {
    route: '/',
    appFile: 'src/app/pages/index.astro',
    domain: 'home',
    surface: 'Owner home / Today',
    wireframes: ['F-A1_mobile_owner_home.html', 'F-A1b_mobile_owner_home_v5_pulse.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Root home should be the phone-first F-A1b home: One Thing, 5 brain questions, On Deck, Pulse, and no visible back button. F-A1 remains the earlier home reference.',
    next: [
      ...homeTabs,
      { trigger: 'One Thing card', route: 'attention.href', face: 'route-specific face', note: 'The attention artifact owns the target route.' },
      { trigger: 'On Deck item', route: 'attention.href', face: 'route-specific face' },
      { trigger: 'Pulse item', route: 'attention.href', face: 'route-specific face' },
    ],
  },
  {
    route: '/home/owner',
    appFile: 'src/app/pages/home/owner.astro',
    domain: 'home',
    surface: 'Owner home role projection',
    wireframes: ['F-A1_mobile_owner_home.html', 'F-A2_desktop_owner_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Role route is registered as F-A2 desktop, but phone should still answer to F-A1. Current visible NavBack is old shell leakage.',
    next: homeTabs,
  },
  {
    route: '/home/pm',
    appFile: 'src/app/pages/home/pm.astro',
    domain: 'home',
    surface: 'PM home',
    wireframes: ['F-P1_mobile_pm_home.html', 'F-P2_desktop_pm_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Currently a role-home stub. Needs real PM home projection.',
    next: [
      { trigger: 'Field capture shortcut', route: '/field-capture', face: 'F-E1_mobile_field_capture.html' },
      { trigger: 'Projects shortcut', route: '/projects', face: 'F-PR1_mobile_projects_list.html' },
      { trigger: 'On me shortcut', route: '/on-me', face: 'F-TD1_mobile_global_todo.html' },
    ],
  },
  {
    route: '/home/admin-ops',
    appFile: 'src/app/pages/home/admin-ops.astro',
    domain: 'home',
    surface: 'Admin/Ops home',
    wireframes: ['F-AO1_mobile_admin_ops_home.html', 'F-AO2_desktop_admin_ops_home.html', 'F-AD3_mobile_admin_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Current role home is a stub projection. F-AD admin landing remains a separate future/admin entry.',
    next: [
      { trigger: 'Field capture shortcut', route: '/field-capture', face: 'F-E1_mobile_field_capture.html' },
      { trigger: 'Projects shortcut', route: '/projects', face: 'F-PR1_mobile_projects_list.html' },
      { trigger: 'On me shortcut', route: '/on-me', face: 'F-TD1_mobile_global_todo.html' },
    ],
  },
  {
    route: '/home/team-ops',
    appFile: 'src/app/pages/home/team-ops.astro',
    domain: 'people_admin_ops',
    surface: 'Team/Ops home',
    wireframes: ['F-TO1_mobile_team_ops_home.html', 'F-TO2_desktop_team_ops_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Current role home is a stub projection.',
    next: [
      { trigger: 'Subs / crew', route: '/team-ops/subs', face: 'F-SB1_mobile_subs_list.html' },
      { trigger: 'Schedule', route: '/schedule', face: 'F-SC1_mobile_schedule_home.html' },
    ],
  },
  {
    route: '/home/sub',
    appFile: 'src/app/pages/home/sub.astro',
    domain: 'home',
    surface: 'Sub home',
    wireframes: ['F-SH1_mobile_sub_home.html', 'F-SH2_desktop_sub_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'surfaceCatalog currently labels this component as SU2; the appropriate sub face is SH1/SH2. SU1/SU2 belong to superintendent.',
    next: [
      { trigger: 'Portal', route: '/sub/portal', face: 'F-SH1_mobile_sub_home.html' },
      { trigger: 'Assignment', route: '/sub/portal/s/:token/a/:assignmentId', face: 'F-W1_mobile_work_order.html' },
    ],
  },
  {
    route: '/home/estimator',
    appFile: 'src/app/pages/home/estimator.astro',
    domain: 'home',
    surface: 'Estimator home',
    wireframes: ['F-ES1_mobile_estimator_home.html', 'F-ES2_desktop_estimator_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Current role home is a stub projection.',
    next: [
      { trigger: 'Sales pipeline', route: '/sales', face: 'F-SL1_mobile_sales_pipeline.html' },
      { trigger: 'Projects', route: '/projects', face: 'F-PR1_mobile_projects_list.html' },
    ],
  },
  {
    route: '/home/field',
    appFile: 'src/app/pages/home/field.astro',
    domain: 'home',
    surface: 'Field hand home',
    wireframes: ['F-C1_mobile_field_hand_home.html', 'F-FH1_mobile_field_hand_home.html', 'F-FL1_mobile_foreman_home.html', 'F-SU1_mobile_superintendent_home.html', 'F-SU2_desktop_superintendent_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Role-specific field, foreman, and superintendent projections need explicit routing by role.',
    next: [
      { trigger: 'Capture', route: '/field-capture', face: 'F-E1_mobile_field_capture.html' },
      { trigger: 'Project detail', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'On me', route: '/on-me', face: 'F-TD1_mobile_global_todo.html' },
    ],
  },
  {
    route: '/create',
    appFile: 'src/app/pages/create.astro',
    domain: 'people_admin_ops',
    surface: 'Start action sheet',
    wireframes: ['F-S1_mobile_start_action_sheet.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Start sheet exists as a page, but the canon sheet grammar was listed as a gap in Goal 0.',
    next: [
      { trigger: 'New estimate', route: '/estimate/:projectId or /projects/new?src=create', face: 'F-EST1_mobile_estimate_builder.html', note: 'Canon face is now present; live route still needs the estimate-first/project-known decision.' },
      { trigger: 'Daily log note', route: '/field-capture?src=create', face: 'F-E1_mobile_field_capture.html' },
      { trigger: 'Change order', route: '/change-orders/new?src=create', face: 'F-CHG1_mobile_change_order_builder.html', note: 'Canon builder face is now present; live route is still pending on the CO branch.' },
      { trigger: 'Invoice', route: '/money?src=create', face: 'F-MN1_mobile_money_home.html' },
      { trigger: 'Room scan / LiDAR', route: '/room-capture?src=create', face: 'F-RC1_mobile_room_capture.html' },
      { trigger: 'Ask Right Hand', route: '/right-hand', face: 'F-RH1_mobile_right_hand_voice_overlay.html' },
    ],
  },
  {
    route: '/right-hand',
    appFile: 'src/app/pages/right-hand.astro',
    domain: 'home',
    surface: 'Right Hand conversation / fallback',
    wireframes: ['F-RH1_mobile_right_hand_voice_overlay.html', 'F-RH3_mobile_right_hand_conversation_lifecycle.html', 'F-RH4_desktop_conversation_compose.html', 'F-RH6_talk_to_right_hand.html', 'F-RH7_bubble_transitions.html'],
    status: 'canon_wired',
    notes: 'F-RH7 is now present in repo canon as the bubble/bloom behavior. This route remains the fallback page when overlay travel cannot keep the operator on artifact.',
    next: [
      { trigger: 'Back', route: 'return_to or referrer', face: 'previous face' },
      { trigger: 'Quick action: add photo', route: '/camera?src=right-hand', face: 'F-CAM1_mobile_camera.html' },
      { trigger: 'Quick action: open job', route: '/projects', face: 'F-PR1_mobile_projects_list.html' },
      { trigger: 'Quick action: review estimate', route: '/estimate/:projectId', face: 'F-ES1_mobile_estimator_home.html' },
      { trigger: 'Quick action: go home', route: '/', face: 'F-A1_mobile_owner_home.html' },
    ],
  },
  {
    route: '/camera',
    appFile: 'src/app/pages/camera.astro',
    domain: 'people_admin_ops',
    surface: 'Camera capture-first',
    wireframes: ['F-CAM1_mobile_camera.html'],
    status: 'canon_wired',
    notes: 'Capture opens first, route panel appears after Done unless project is prefilled. Phone gate still owns actual viewport/tap validation.',
    next: [
      { trigger: 'Close X', route: 'return_to or /', face: 'previous face' },
      { trigger: 'Room scan', route: '/room-capture?src=camera&mode=start', face: 'F-RC1_mobile_room_capture.html' },
      { trigger: 'Search jobs', route: '/projects?src=camera', face: 'F-PR1_mobile_projects_list.html' },
      { trigger: 'New client / lead', route: '/clients/new?src=camera', face: 'F-CL0a_mobile_client_create.html', note: 'Capture-first route when the evidence belongs to a new lead/client.' },
      { trigger: 'New project', route: '/projects/new?src=camera', face: 'F-PR0a_mobile_project_setup.html', note: 'Capture-first route when the job does not exist yet.' },
      { trigger: 'Save to review', route: '/relay?src=camera', face: 'F-FU1_mobile_field_updates_review.html', note: 'Holding path when destination is not known yet.' },
      { trigger: 'Confirm and file', route: '/projects/:id?src=camera', face: 'F-PR2_mobile_project_detail.html', note: 'Filed capture should surface Daily Log handoff.' },
    ],
  },
  {
    route: '/field-capture',
    appFile: 'src/app/pages/field-capture.astro',
    domain: 'field',
    surface: 'Field capture',
    wireframes: ['F-E1_mobile_field_capture.html'],
    status: 'canon_wired',
    notes: 'Capture-first field note surface; destination selected in preflight.',
    next: [
      { trigger: 'Back/cancel', route: 'return_to or /', face: 'previous face' },
      { trigger: 'Photo', route: '/camera?src=field-capture', face: 'F-CAM1_mobile_camera.html' },
      { trigger: 'Open office review', route: '/relay', face: 'F-FU1_mobile_field_updates_review.html' },
      { trigger: 'Transcript review', route: '/transcript-review', face: 'F-F1_desktop_transcript_review.html' },
      { trigger: 'Draft preview', route: '/draft-review/:draft_id', face: 'F-G1_desktop_draft_review.html' },
      { trigger: 'Field detail', route: '/field-detail', face: 'F-FD1_mobile_field_detail.html' },
    ],
  },
  {
    route: '/field',
    appFile: 'src/app/pages/field.astro',
    domain: 'field',
    surface: 'Field home',
    wireframes: ['F-C1_mobile_field_hand_home.html', 'F-FL1_mobile_foreman_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Operational field home outside role-root home.',
    next: [
      { trigger: 'Capture', route: '/field-capture', face: 'F-E1_mobile_field_capture.html' },
      { trigger: 'Field detail', route: '/field-detail', face: 'F-FD1_mobile_field_detail.html' },
      { trigger: 'Projects', route: '/projects', face: 'F-PR1_mobile_projects_list.html' },
    ],
  },
  {
    route: '/field-detail',
    appFile: 'src/app/pages/field-detail.astro',
    domain: 'field',
    surface: 'Field detail',
    wireframes: ['F-FD1_mobile_field_detail.html', 'F-FD2_desktop_field_detail.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Detail/drill face for a field item.',
    next: [
      { trigger: 'Back to field', route: '/field', face: 'F-C1_mobile_field_hand_home.html' },
      { trigger: 'Capture', route: '/field-capture', face: 'F-E1_mobile_field_capture.html' },
    ],
  },
  {
    route: '/relay',
    appFile: 'src/app/pages/relay/index.astro',
    domain: 'field',
    surface: 'Field updates review',
    wireframes: ['F-FU1_mobile_field_updates_review.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Office review queue for field updates.',
    next: [
      { trigger: 'Relay card', route: '/relay/:id', face: 'F-FU1_mobile_field_updates_review.html' },
      { trigger: 'Project', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
    ],
  },
  {
    route: '/relay/:id',
    appFile: 'src/app/pages/relay/[id].astro',
    domain: 'field',
    surface: 'Relay detail',
    wireframes: ['F-FU1_mobile_field_updates_review.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Drill state of field updates review; no separate canon detail file in repo.',
    next: [
      { trigger: 'Back', route: '/relay', face: 'F-FU1_mobile_field_updates_review.html' },
      { trigger: 'Open project', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
    ],
  },
  {
    route: '/transcript-review',
    appFile: 'src/app/pages/transcript-review.astro',
    domain: 'client_success',
    surface: 'Transcript review',
    wireframes: ['F-F1_desktop_transcript_review.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Review/classification surface for captured transcript facts.',
    next: [
      { trigger: 'Field capture', route: '/field-capture', face: 'F-E1_mobile_field_capture.html' },
      { trigger: 'Continue draft', route: '/draft-review/:draft_id', face: 'F-G1_desktop_draft_review.html' },
    ],
  },
  {
    route: '/room-capture',
    appFile: 'src/app/pages/room-capture.astro',
    domain: 'field',
    surface: 'Room capture / LiDAR',
    wireframes: ['F-RC1_mobile_room_capture.html', 'F-RT1_desktop_room_takeoff.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Room capture face entered from Camera or Start.',
    next: [
      { trigger: 'Back', route: '/camera or /create or /', face: 'previous face' },
      { trigger: 'View demo scan', route: '/room-capture?scan_id=demo_last', face: 'F-RC1_mobile_room_capture.html' },
      { trigger: 'Add to project', route: '/projects/proj_wegrzyn_kitchen', face: 'F-PR2_mobile_project_detail.html' },
    ],
  },
  {
    route: '/projects',
    appFile: 'src/app/pages/projects/index.astro',
    domain: 'projects',
    surface: 'Projects list',
    wireframes: ['F-PR1_mobile_projects_list.html', 'F-PR3_desktop_projects_list.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Project archive/list entry.',
    next: [
      { trigger: 'Project row', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'New project', route: '/projects/new', face: 'F-PR0a_mobile_project_setup.html' },
    ],
  },
  {
    route: '/projects/new',
    appFile: 'src/app/pages/projects/new.astro',
    domain: 'projects',
    surface: 'New project / project setup',
    wireframes: ['F-PR0a_mobile_project_setup.html', 'F-PR0b_desktop_project_setup.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Dedicated mobile/desktop project setup faces are now present. Live form should match them and support new project creation from client, sales, and capture routing.',
    next: [
      { trigger: 'Cancel', route: '/projects or /clients/:id', face: 'F-PR1_mobile_projects_list.html' },
      { trigger: 'Submit', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
    ],
  },
  {
    route: '/projects/:id',
    appFile: 'src/app/pages/projects/[id]/index.astro',
    domain: 'projects',
    surface: 'Project detail',
    wireframes: ['F-PR2_mobile_project_detail.html', 'F-PR4_desktop_project_detail.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Project canonical home. Lenses should not become disconnected document surfaces.',
    next: [
      { trigger: 'Daily Log', route: '/projects/:id/daily-log', face: 'F-DL1_mobile_daily_log.html', note: 'Canon face is present; live route is still pending on the Daily Log branch.' },
      { trigger: 'Status', route: '/projects/:id/status', face: 'F-PS1_mobile_project_status.html' },
      { trigger: 'Portal preview', route: '/projects/:id/portal-preview', face: 'F-CS1_mobile_client_success.html' },
      { trigger: 'Work order', route: '/projects/:id/work-orders/:wid', face: 'F-W1_mobile_work_order.html' },
      { trigger: 'Closeout', route: '/projects/:id/closeout', face: 'F-CO1a_mobile_closeout.html' },
      { trigger: 'Camera landed Daily Log', route: '/projects/:id/daily-log', face: 'F-DL1_mobile_daily_log.html' },
    ],
  },
  {
    route: '/projects/:id/daily-log',
    domain: 'projects',
    surface: 'Daily Log',
    wireframes: ['F-DL1_mobile_daily_log.html', 'F-DL2_mobile_field_hand_daily_log_clockout.html'],
    status: 'future_or_unrouted',
    notes: 'F-DL1 is now present in repo canon. The flat Daily Log route is still pending merge from the Daily Log implementation branch.',
    next: [
      { trigger: 'Add media', route: '/camera?return_to=/projects/:id/daily-log', face: 'F-CAM1_mobile_camera.html' },
      { trigger: 'File / done', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'Office review', route: '/relay', face: 'F-FU1_mobile_field_updates_review.html' },
    ],
  },
  {
    route: '/projects/:id/:tab',
    appFile: 'src/app/pages/projects/[id]/[tab].astro',
    domain: 'projects',
    surface: 'Project detail tab/lens',
    wireframes: ['F-PR2_mobile_project_detail.html', 'F-PR4_desktop_project_detail.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Tabbed lens state of project detail, not a separate artifact owner.',
    next: [
      { trigger: 'Tab strip', route: '/projects/:id/:tab', face: 'F-PR2_mobile_project_detail.html' },
    ],
  },
  {
    route: '/projects/:id/status',
    appFile: 'src/app/pages/projects/[id]/status.astro',
    domain: 'projects',
    surface: 'Project status',
    wireframes: ['F-PS1_mobile_project_status.html', 'F-CPS1_mobile_client_project_status.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Project status should be a project lens, not an orphan dashboard.',
    next: [
      { trigger: 'Back to scope', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'Audit', route: '/audit/:packetId', face: 'F-H1_desktop_audit_detail.html' },
      { trigger: 'Relay', route: '/relay', face: 'F-FU1_mobile_field_updates_review.html' },
    ],
  },
  {
    route: '/projects/:id/closeout',
    appFile: 'src/app/pages/projects/[id]/closeout.astro',
    domain: 'projects',
    surface: 'Project closeout',
    wireframes: ['F-CO1a_mobile_closeout.html', 'F-CO1b_desktop_closeout.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Closeout is owned by the project, with audit linkout.',
    next: [
      { trigger: 'Back project', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'Audit', route: '/audit/:packetId', face: 'F-H1_desktop_audit_detail.html' },
    ],
  },
  {
    route: '/projects/:id/portal-preview',
    appFile: 'src/app/pages/projects/[id]/portal-preview.astro',
    domain: 'clients',
    surface: 'Client portal preview',
    wireframes: ['F-CS1_mobile_client_success.html', 'F-CS2_desktop_client_success.html', 'F-CP1_desktop_client_portal.html', 'F-CPS1_mobile_client_project_status.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Operator preview of client-facing portal. There is no specific portal-preview canon file in this repo.',
    next: [
      { trigger: 'Back project', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'Open client login', route: '/portal/s/:token', face: 'client portal face missing from repo' },
    ],
  },
  {
    route: '/projects/:id/work-orders/:wid',
    appFile: 'src/app/pages/projects/[id]/work-orders/[wid].astro',
    domain: 'projects',
    surface: 'Work order',
    wireframes: ['F-W1_mobile_work_order.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Work order is project-owned and should not float as a generic task.',
    next: [
      { trigger: 'Back project', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'Sub assignment', route: '/sub/portal/s/:token/a/:assignmentId', face: 'F-W1_mobile_work_order.html' },
    ],
  },
  {
    route: '/design/:projectId',
    appFile: 'src/app/pages/design/[projectId].astro',
    domain: 'sales',
    surface: 'Design workspace',
    wireframes: ['F-SL3_mobile_deal_detail.html', 'F-SL4_desktop_deal_detail.html', 'F-DES1a_mobile_design_workspace.html', 'F-DS1_desktop_design_workspace.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Mobile and desktop Canon faces are now present. The live route sits between deal detail and estimate and needs a rebuild to match F-DES1a/F-DS1.',
    next: [
      { trigger: 'Deal back', route: '/sales/:id', face: 'F-SL3_mobile_deal_detail.html' },
      { trigger: 'Open KB', route: '/library', face: 'cost knowledge face missing from repo' },
      { trigger: 'Build estimate', route: '/estimate/:projectId', face: 'F-EST1_mobile_estimate_builder.html' },
    ],
  },
  {
    route: '/estimate/:projectId',
    appFile: 'src/app/pages/estimate/[projectId].astro',
    domain: 'sales',
    surface: 'Estimate builder',
    wireframes: ['F-EST1_mobile_estimate_builder.html', 'F-ES1_mobile_estimator_home.html', 'F-ES2_desktop_estimator_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'F-EST1 is now present in repo canon. Live estimate builder must be rebuilt to this face while preserving proposal/invoice line_id carry.',
    next: [
      { trigger: 'Back', route: '/design/:projectId or /sales/:id', face: 'F-SL3_mobile_deal_detail.html' },
      { trigger: 'Open Right Hand draft', route: '/right-hand', face: 'F-RH1_mobile_right_hand_voice_overlay.html' },
      { trigger: 'Download workbook', route: '/api/v1/right-hand/estimates/:id/workbook', face: 'file download, no face' },
      { trigger: 'Convert to project', route: '/estimate/:projectId?estimate_id=:id', face: 'F-EST1_mobile_estimate_builder.html' },
      { trigger: 'Proposal open/generate', route: '/estimate/:projectId/proposal', face: 'F-PV1_mobile_proposal_view.html' },
      { trigger: 'Invoice open', route: '/estimate/:projectId/invoice', face: 'F-INV1a_mobile_per_job_invoice_list.html' },
      { trigger: 'Money open', route: '/estimate/:projectId/money', face: 'F-MN1_mobile_money_home.html' },
    ],
  },
  {
    route: '/change-orders/new',
    appFile: 'src/app/pages/change-orders/new.astro',
    domain: 'sales',
    surface: 'Change order builder',
    wireframes: ['F-CHG1_mobile_change_order_builder.html'],
    status: 'canon_wired',
    notes: 'F-CHG1 builder route exists on the Change Order implementation branch. Submit routes to the F-B1 Decision Card instead of a generic draft state.',
    next: [
      { trigger: 'Back project', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'Submit for approval', route: '/decisions/:id', face: 'F-B1_mobile_decision_card.html' },
      { trigger: 'Ask Right Hand', route: '/right-hand', face: 'F-RH1_mobile_right_hand_voice_overlay.html' },
    ],
  },
  {
    route: '/projects/:id/change-order',
    appFile: 'src/app/pages/projects/[id]/change-order.astro',
    domain: 'sales',
    surface: 'Project change order entry',
    wireframes: ['F-CHG1_mobile_change_order_builder.html'],
    status: 'redirect',
    notes: 'Project-owned entry point for change orders. It preserves project context and redirects to /change-orders/new?project_id=:id, where the F-CHG1 builder owns the artifact.',
    next: [
      { trigger: 'Open builder', route: '/change-orders/new?project_id=:id', face: 'F-CHG1_mobile_change_order_builder.html' },
    ],
  },
  {
    route: '/estimate/:projectId/proposal',
    appFile: 'src/app/pages/estimate/[projectId]/proposal.astro',
    domain: 'sales',
    surface: 'Proposal projection',
    wireframes: ['F-PV1_mobile_proposal_view.html', 'F-PV2_desktop_proposal_view.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Proposal is a projection of estimate lines, not an RH-owned artifact.',
    next: [
      { trigger: 'Back estimate', route: '/estimate/:projectId', face: 'F-EST1_mobile_estimate_builder.html' },
      { trigger: 'Open printable draft', route: '/api/v1/right-hand/estimates/:id/proposal', face: 'print artifact, F-PV1 projection' },
      { trigger: 'Open Money', route: '/estimate/:projectId/money', face: 'F-MN1_mobile_money_home.html' },
      { trigger: 'Create down-payment invoice', route: '/estimate/:projectId/invoice', face: 'F-INV1a_mobile_per_job_invoice_list.html' },
    ],
  },
  {
    route: '/estimate/:projectId/invoice',
    appFile: 'src/app/pages/estimate/[projectId]/invoice.astro',
    domain: 'money',
    surface: 'Per-job invoice',
    wireframes: ['F-INV1a_mobile_per_job_invoice_list.html', 'F-INV1b_desktop_per_job_invoice_list.html', 'F-INV2a_mobile_per_job_invoice_detail.html', 'F-INV2b_desktop_per_job_invoice_detail.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Canon per-job invoice list/detail faces are now present. Live route must rebuild away from AR aging into deposit/progress/final invoice list with money_guard detail drill and line_id carry.',
    next: [
      { trigger: 'Back estimate', route: '/estimate/:projectId', face: 'F-EST1_mobile_estimate_builder.html' },
      { trigger: 'Back proposal', route: '/estimate/:projectId/proposal', face: 'F-PV1_mobile_proposal_view.html' },
      { trigger: 'Open Money', route: '/estimate/:projectId/money', face: 'F-MN1_mobile_money_home.html' },
      { trigger: 'Open invoice detail', route: '/estimate/:projectId/invoice/:invoiceId or /money/invoices/:id', face: 'F-INV2a_mobile_per_job_invoice_detail.html' },
      { trigger: 'Open printable draft', route: '/api/v1/right-hand/estimates/:id/invoice', face: 'print artifact, invoice projection' },
    ],
  },
  {
    route: '/estimate/:projectId/money',
    appFile: 'src/app/pages/estimate/[projectId]/money.astro',
    domain: 'money',
    surface: 'Project money lens',
    wireframes: ['F-MN1_mobile_money_home.html', 'F-MN2_desktop_money_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Project-scoped money lens; should deep-link to global Money without hiding project ownership.',
    next: [
      { trigger: 'Back estimate', route: '/estimate/:projectId', face: 'F-EST1_mobile_estimate_builder.html' },
      { trigger: 'Global Money', route: '/money', face: 'F-MN1_mobile_money_home.html' },
    ],
  },
  {
    route: '/proposals/:id/preview',
    appFile: 'src/app/pages/proposals/[id]/preview.astro',
    domain: 'sales',
    surface: 'Proposal preview/send prep',
    wireframes: ['F-PV1_mobile_proposal_view.html', 'F-PV2_desktop_proposal_view.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Tenant-scoped consequential read. Preview remains proposal-owned, not chat-owned.',
    next: [
      { trigger: 'Back draft', route: '/draft-review', face: 'F-G1_desktop_draft_review.html' },
      { trigger: 'Send', route: '/proposals/:id/send', face: 'F-B1c_mobile_decision_card_client_preview.html' },
    ],
  },
  {
    route: '/proposals/:id/send',
    appFile: 'src/app/pages/proposals/[id]/send.astro',
    domain: 'sales',
    surface: 'Proposal send gate',
    wireframes: ['F-B1c_mobile_decision_card_client_preview.html', 'F-PV2_desktop_proposal_view.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Visible send gate. No silent external send.',
    next: [
      { trigger: 'Back fix', route: '/draft-review', face: 'F-G1_desktop_draft_review.html' },
      { trigger: 'Confirm send', route: 'same route/API consequence', face: 'F-B1c_mobile_decision_card_client_preview.html' },
    ],
  },
  {
    route: '/sales',
    appFile: 'src/app/pages/sales/index.astro',
    domain: 'sales',
    surface: 'Sales pipeline',
    wireframes: ['F-SL1_mobile_sales_pipeline.html', 'F-SL2_desktop_sales_pipeline.html', 'F-SA1_mobile_sales_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Pipeline/home for win-the-work.',
    next: [
      { trigger: 'Deal card', route: '/sales/:id', face: 'F-SL3_mobile_deal_detail.html' },
    ],
  },
  {
    route: '/sales/:id',
    appFile: 'src/app/pages/sales/[id].astro',
    domain: 'sales',
    surface: 'Deal detail',
    wireframes: ['F-SL3_mobile_deal_detail.html', 'F-SL4_desktop_deal_detail.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Lead/deal surface leading to design and estimate.',
    next: [
      { trigger: 'Pipeline back', route: '/sales', face: 'F-SL1_mobile_sales_pipeline.html' },
      { trigger: 'Open Design workspace', route: '/design/:projectId', face: 'F-DES1a_mobile_design_workspace.html' },
      { trigger: 'Estimate builder', route: '/estimate/:projectId', face: 'F-EST1_mobile_estimate_builder.html' },
    ],
  },
  {
    route: '/draft-review',
    appFile: 'src/app/pages/draft-review.astro',
    domain: 'projects',
    surface: 'Draft review redirect',
    wireframes: ['F-G1_desktop_draft_review.html'],
    status: 'redirect',
    notes: 'Redirects to fixture draft review detail.',
    next: [
      { trigger: 'Redirect', route: '/draft-review/:draft_id', face: 'F-G1_desktop_draft_review.html' },
    ],
  },
  {
    route: '/draft-review/:draft_id',
    appFile: 'src/app/pages/draft-review/[draft_id].astro',
    domain: 'projects',
    surface: 'Draft review',
    wireframes: ['F-G1_desktop_draft_review.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Review gate for draft artifacts.',
    next: [
      { trigger: 'Open job', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'Preview', route: '/proposals/:id/preview', face: 'F-PV1_mobile_proposal_view.html' },
      { trigger: 'Accept', route: '/proposals/:id/preview', face: 'F-PV1_mobile_proposal_view.html' },
      { trigger: 'Reject', route: 'return_to', face: 'previous face' },
    ],
  },
  {
    route: '/decisions',
    appFile: 'src/app/pages/decisions/index.astro',
    domain: 'sales',
    surface: 'Decision cards hub',
    wireframes: ['F-B1_mobile_decision_card.html', 'F-B2_desktop_decision_card.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Decision hub has no separate list face. It should present B1 cards, not a generic dashboard.',
    next: [
      { trigger: 'Decision card', route: '/decisions/:id', face: 'F-B1_mobile_decision_card.html' },
    ],
  },
  {
    route: '/decisions/:id',
    appFile: 'src/app/pages/decisions/[id].astro',
    domain: 'sales',
    surface: 'Decision card',
    wireframes: ['F-B1_mobile_decision_card.html', 'F-B1b_mobile_decision_card_edit.html', 'F-B1c_mobile_decision_card_client_preview.html', 'F-B2_desktop_decision_card.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Change-order decision gate should approve/reject/edit, then adjust contract behind the gate.',
    next: [
      { trigger: 'Approve', route: 'same route/API consequence', face: 'F-B1_mobile_decision_card.html' },
      { trigger: 'Edit', route: '/decisions/:id?mode=edit', face: 'F-B1b_mobile_decision_card_edit.html' },
      { trigger: 'Client preview', route: '/proposals/:id/send', face: 'F-B1c_mobile_decision_card_client_preview.html' },
      { trigger: 'Project audit', route: '/audit/:packetId', face: 'F-H1_desktop_audit_detail.html' },
    ],
  },
  {
    route: '/money',
    appFile: 'src/app/pages/money/index.astro',
    domain: 'money',
    surface: 'Money home',
    wireframes: ['F-MN1_mobile_money_home.html', 'F-MN2_desktop_money_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Global money domain: invoices, AP, AR, allowances, margin, bookkeeping.',
    next: [
      { trigger: 'AR', route: '/money/ar', face: 'F-MN6a_mobile_ar_aging.html' },
      { trigger: 'AP', route: '/money/ap', face: 'F-MN7a_mobile_ap_scheduling.html' },
      { trigger: 'Allowances', route: '/money/allowances', face: 'F-MN5a_mobile_allowance_exceptions.html' },
      { trigger: 'Bookkeeping', route: '/money/bookkeeping', face: 'F-BK1a_mobile_bookkeeping_recon.html' },
      { trigger: 'QB export', route: '/money/qb-export', face: 'F-BK2_desktop_qb_export.html' },
      { trigger: 'Margin', route: '/money/margin', face: 'F-MN3_mobile_margin_posture.html' },
    ],
  },
  {
    route: '/money/ar',
    appFile: 'src/app/pages/money/ar.astro',
    domain: 'money',
    surface: 'AR aging',
    wireframes: ['F-MN6a_mobile_ar_aging.html', 'F-MN6b_desktop_ar_aging.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Money-grade AR view. Consequential reads must be tenant-scoped.',
    next: [
      { trigger: 'Back Money', route: '/money', face: 'F-MN1_mobile_money_home.html' },
    ],
  },
  {
    route: '/money/ap',
    appFile: 'src/app/pages/money/ap.astro',
    domain: 'money',
    surface: 'AP scheduling',
    wireframes: ['F-MN7a_mobile_ap_scheduling.html', 'F-MN7b_desktop_ap_scheduling.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Money-grade AP view. Consequential reads must be tenant-scoped.',
    next: [
      { trigger: 'Back Money', route: '/money', face: 'F-MN1_mobile_money_home.html' },
    ],
  },
  {
    route: '/money/allowances',
    appFile: 'src/app/pages/money/allowances.astro',
    domain: 'money',
    surface: 'Allowance exceptions',
    wireframes: ['F-MN5a_mobile_allowance_exceptions.html', 'F-MN5b_desktop_allowance_exceptions.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Allowance exception queue.',
    next: [
      { trigger: 'Back Money', route: '/money', face: 'F-MN1_mobile_money_home.html' },
    ],
  },
  {
    route: '/money/bookkeeping',
    appFile: 'src/app/pages/money/bookkeeping.astro',
    domain: 'money',
    surface: 'Bookkeeping reconciliation',
    wireframes: ['F-BK1a_mobile_bookkeeping_recon.html', 'F-BK1b_desktop_bookkeeping_recon.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Bookkeeping recon view.',
    next: [
      { trigger: 'Back Money', route: '/money', face: 'F-MN1_mobile_money_home.html' },
    ],
  },
  {
    route: '/money/qb-export',
    appFile: 'src/app/pages/money/qb-export.astro',
    domain: 'money',
    surface: 'QuickBooks export',
    wireframes: ['F-BK2_desktop_qb_export.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Desktop-only export framing in repo canon.',
    next: [
      { trigger: 'Back Money', route: '/money', face: 'F-MN1_mobile_money_home.html' },
    ],
  },
  {
    route: '/money/margin',
    appFile: 'src/app/pages/money/margin.astro',
    domain: 'money',
    surface: 'Margin posture',
    wireframes: ['F-MN3_mobile_margin_posture.html', 'F-MN4_desktop_margin_posture.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Owner-only money posture.',
    next: [
      { trigger: 'Back Money', route: '/money', face: 'F-MN1_mobile_money_home.html' },
    ],
  },
  {
    route: '/clients',
    appFile: 'src/app/pages/clients/index.astro',
    domain: 'clients',
    surface: 'Clients list',
    wireframes: ['F-CL1_mobile_clients_list.html', 'F-CL3_desktop_clients_list.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Client index.',
    next: [
      { trigger: 'New client', route: '/clients/new', face: 'F-CL0a_mobile_client_create.html' },
      { trigger: 'Client row', route: '/clients/:id', face: 'F-CL5_mobile_client_record.html' },
    ],
  },
  {
    route: '/clients/new',
    appFile: 'src/app/pages/clients/new.astro',
    domain: 'clients',
    surface: 'New client',
    wireframes: ['F-CL0a_mobile_client_create.html', 'F-CL0b_desktop_client_create.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Dedicated mobile/desktop client-create faces are now present. Live form should match them and remain an operator-confirmed client graph write.',
    next: [
      { trigger: 'Cancel', route: '/clients', face: 'F-CL1_mobile_clients_list.html' },
      { trigger: 'Submit', route: '/clients/:id', face: 'F-CL5_mobile_client_record.html' },
    ],
  },
  {
    route: '/clients/:id',
    appFile: 'src/app/pages/clients/[id].astro',
    domain: 'clients',
    surface: 'Client record/detail',
    wireframes: ['F-CL2_mobile_client_detail.html', 'F-CL4_desktop_client_detail.html', 'F-CL5_mobile_client_record.html', 'F-CL6_desktop_client_record.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Client canonical home. Projects and warranty drill from here.',
    next: [
      { trigger: 'Back clients', route: '/clients', face: 'F-CL1_mobile_clients_list.html' },
      { trigger: 'New project', route: '/projects/new?client_id=:id', face: 'F-PR0a_mobile_project_setup.html' },
      { trigger: 'Client success', route: '/client-success/:clientId', face: 'F-CS1_mobile_client_success.html' },
      { trigger: 'Warranty', route: '/clients/:id/warranty', face: 'F-WW1a_mobile_warranty.html' },
      { trigger: 'Project row', route: '/projects/:id', face: 'F-PR2_mobile_project_detail.html' },
      { trigger: 'Portal preview', route: '/projects/:id/portal-preview', face: 'F-CS1_mobile_client_success.html' },
    ],
  },
  {
    route: '/clients/:id/warranty',
    appFile: 'src/app/pages/clients/[id]/warranty.astro',
    domain: 'clients',
    surface: 'Warranty',
    wireframes: ['F-WW1a_mobile_warranty.html', 'F-WW1b_desktop_warranty.html', 'F-WAR1_desktop_warranty.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Client-owned warranty lane.',
    next: [
      { trigger: 'Back client', route: '/clients/:id', face: 'F-CL5_mobile_client_record.html' },
    ],
  },
  {
    route: '/client-success',
    appFile: 'src/app/pages/client-success/index.astro',
    domain: 'client_success',
    surface: 'Client success',
    wireframes: ['F-CS1_mobile_client_success.html', 'F-CS2_desktop_client_success.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Client success list/health view.',
    next: [
      { trigger: 'Client row', route: '/client-success/:clientId', face: 'F-CS1_mobile_client_success.html' },
    ],
  },
  {
    route: '/client-success/:clientId',
    appFile: 'src/app/pages/client-success/[clientId].astro',
    domain: 'client_success',
    surface: 'Client success detail',
    wireframes: ['F-CS1_mobile_client_success.html', 'F-CS2_desktop_client_success.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Detail/drill state of client success; no separate canon detail file.',
    next: [
      { trigger: 'Client record', route: '/clients/:id', face: 'F-CL5_mobile_client_record.html' },
      { trigger: 'Warranty', route: '/clients/:id/warranty', face: 'F-WW1a_mobile_warranty.html' },
    ],
  },
  {
    route: '/schedule',
    appFile: 'src/app/pages/schedule.astro',
    domain: 'schedule',
    surface: 'Schedule',
    wireframes: ['F-SC1_mobile_schedule_home.html', 'F-SC2_desktop_schedule_home.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Schedule domain home.',
    next: [
      { trigger: 'Subs', route: '/team-ops/subs', face: 'F-SB1_mobile_subs_list.html' },
    ],
  },
  {
    route: '/team-ops/subs',
    appFile: 'src/app/pages/team-ops/subs.astro',
    domain: 'people_admin_ops',
    surface: 'Subs / crew',
    wireframes: ['F-SB1_mobile_subs_list.html', 'F-SB2_desktop_subs_list.html', 'F-CR1_mobile_crew.html', 'F-CR2_desktop_crew.html', 'F-SUBM1_desktop_subs_management.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Subcontractor and crew operations. Crew faces are currently folded into this route.',
    next: [
      { trigger: 'Send WO', route: '/sub/portal/s/:token/a/:assignmentId', face: 'F-W1_mobile_work_order.html' },
      { trigger: 'Message via relay', route: '/relay', face: 'F-FU1_mobile_field_updates_review.html' },
    ],
  },
  {
    route: '/reports',
    appFile: 'src/app/pages/reports.astro',
    domain: 'people_admin_ops',
    surface: 'Reports center / audit portfolio',
    wireframes: ['F-RP1_mobile_reports_center.html', 'F-RP2_desktop_reports_center.html', 'F-AV1a_mobile_audit_portfolio.html', 'F-AV1b_desktop_audit_portfolio.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Reports is the route home; audit portfolio is currently folded into reports/audit.',
    next: [
      { trigger: 'Audit packet', route: '/audit/:packetId', face: 'F-H1_desktop_audit_detail.html' },
    ],
  },
  {
    route: '/audit/:packetId',
    appFile: 'src/app/pages/audit/[packetId].astro',
    domain: 'people_admin_ops',
    surface: 'Audit detail',
    wireframes: ['F-H1_desktop_audit_detail.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Audit packet detail.',
    next: [
      { trigger: 'Back reports', route: '/reports', face: 'F-RP1_mobile_reports_center.html' },
    ],
  },
  {
    route: '/settings',
    appFile: 'src/app/pages/settings.astro',
    domain: 'people_admin_ops',
    surface: 'Settings',
    wireframes: ['F-SP1_desktop_settings.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Admin/settings center.',
    next: [
      { trigger: 'Your settings', route: '/settings/me', face: 'F-SP1a_desktop_account_editor.html' },
      { trigger: 'Connections', route: '/connections', face: 'F-UTIL1b_desktop_connections_kb_blackboard.html' },
      { trigger: 'Project audit', route: '/audit/:packetId', face: 'F-H1_desktop_audit_detail.html' },
    ],
  },
  {
    route: '/settings/me',
    appFile: 'src/app/pages/settings/me.astro',
    domain: 'people_admin_ops',
    surface: 'Account editor',
    wireframes: ['F-SP1a_desktop_account_editor.html', 'F-US1_user_settings.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Personal account settings.',
    next: [
      { trigger: 'Back settings', route: '/settings', face: 'F-SP1_desktop_settings.html' },
    ],
  },
  {
    route: '/connections',
    appFile: 'src/app/pages/connections.astro',
    domain: 'people_admin_ops',
    surface: 'Connections',
    wireframes: ['F-UTIL1a_mobile_connections_kb_blackboard.html', 'F-UTIL1b_desktop_connections_kb_blackboard.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Utility Canon faces now cover the admin-gated connections state.',
    next: [
      { trigger: 'Back settings', route: '/settings', face: 'F-SP1_desktop_settings.html' },
      { trigger: 'Cost knowledge review', route: '/kb-ingestion', face: 'F-UTIL1b_desktop_connections_kb_blackboard.html' },
      { trigger: 'Blackboard preview', route: '/blackboard', face: 'F-UTIL1b_desktop_connections_kb_blackboard.html' },
    ],
  },
  {
    route: '/role-routing',
    appFile: 'src/app/pages/role-routing.astro',
    domain: 'people_admin_ops',
    surface: 'Role root routing matrix',
    wireframes: ['F-RR1_role_root_routing_matrix.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Role routing/admin matrix.',
    next: [
      { trigger: 'Back settings', route: '/settings', face: 'F-SP1_desktop_settings.html' },
    ],
  },
  {
    route: '/more',
    appFile: 'src/app/pages/more.astro',
    domain: 'people_admin_ops',
    surface: 'More sidebar',
    wireframes: ['F-D1_mobile_more_sidebar.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Phone More sheet/sidebar. Holds secondary domains.',
    next: [
      { trigger: 'Schedule', route: '/schedule', face: 'F-SC1_mobile_schedule_home.html' },
      { trigger: 'Reports', route: '/reports', face: 'F-RP1_mobile_reports_center.html' },
      { trigger: 'Settings', route: '/settings', face: 'F-SP1_desktop_settings.html' },
      { trigger: 'Transcript review', route: '/transcript-review', face: 'F-F1_desktop_transcript_review.html' },
      { trigger: 'Decisions', route: '/decisions', face: 'F-B1_mobile_decision_card.html' },
      { trigger: 'Blackboard', route: '/blackboard', face: 'F-UTIL1a_mobile_connections_kb_blackboard.html' },
      { trigger: 'Cost KB', route: '/kb-ingestion', face: 'F-UTIL1a_mobile_connections_kb_blackboard.html' },
      { trigger: 'Clients', route: '/clients', face: 'F-CL1_mobile_clients_list.html' },
    ],
  },
  {
    route: '/on-me',
    appFile: 'src/app/pages/on-me.astro',
    domain: 'home',
    surface: 'Global to-do / On me',
    wireframes: ['F-TD1_mobile_global_todo.html', 'F-TD2_desktop_global_todo.html', 'F-ON1_desktop_on_me_today.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Global personal queue.',
    next: [
      { trigger: 'Task item', route: 'task.href', face: 'route-specific face' },
    ],
  },
  {
    route: '/library',
    appFile: 'src/app/pages/library.astro',
    domain: 'sales',
    surface: 'Cost knowledge library',
    wireframes: ['F-LIB1_desktop_libraries_selections.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Live KB/library route now has the F-LIB1 desktop libraries + selections Canon face.',
    next: [
      { trigger: 'Back design', route: '/design/:projectId', face: 'F-SL3_mobile_deal_detail.html' },
    ],
  },
  {
    route: '/kb-ingestion',
    appFile: 'src/app/pages/kb-ingestion/index.astro',
    domain: 'people_admin_ops',
    surface: 'Cost knowledge ingestion',
    wireframes: ['F-UTIL1a_mobile_connections_kb_blackboard.html', 'F-UTIL1b_desktop_connections_kb_blackboard.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Utility Canon faces now cover the review-only cost knowledge ingestion state.',
    next: [
      { trigger: 'Knowledge item', route: '/kb-ingestion/:id', face: 'F-UTIL1b_desktop_connections_kb_blackboard.html' },
      { trigger: 'Blackboard preview', route: '/blackboard', face: 'F-UTIL1b_desktop_connections_kb_blackboard.html' },
    ],
  },
  {
    route: '/kb-ingestion/:id',
    appFile: 'src/app/pages/kb-ingestion/[id].astro',
    domain: 'people_admin_ops',
    surface: 'Cost knowledge ingestion detail',
    wireframes: ['F-UTIL1a_mobile_connections_kb_blackboard.html', 'F-UTIL1b_desktop_connections_kb_blackboard.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Utility Canon faces cover the KB detail/review state until a dedicated detail face supersedes it.',
    next: [
      { trigger: 'Back KB', route: '/kb-ingestion', face: 'F-UTIL1b_desktop_connections_kb_blackboard.html' },
      { trigger: 'Projects', route: '/projects', face: 'F-PR1_mobile_projects_list.html' },
      { trigger: 'Proposal preview', route: '/proposals/:id/preview', face: 'F-PV1_mobile_proposal_view.html' },
    ],
  },
  {
    route: '/blackboard',
    appFile: 'src/app/pages/blackboard.astro',
    domain: 'projects',
    surface: 'Blackboard',
    wireframes: ['F-UTIL1a_mobile_connections_kb_blackboard.html', 'F-UTIL1b_desktop_connections_kb_blackboard.html'],
    status: 'mapped_pending_rebuild',
    notes: 'Utility Canon faces now cover the read-only Blackboard preview state; no hidden memory writes.',
    next: [
      { trigger: 'Action link', route: 'link.href', face: 'route-specific face' },
      { trigger: 'Audit detail', route: '/audit/:packetId', face: 'F-H1_desktop_audit_detail.html' },
    ],
  },
  {
    route: '/dashboard',
    appFile: 'src/app/pages/dashboard.astro',
    domain: 'home',
    surface: 'Dashboard redirect',
    wireframes: ['F-A1_mobile_owner_home.html'],
    status: 'redirect',
    notes: 'Redirects to root home.',
    next: [
      { trigger: 'Redirect', route: '/', face: 'F-A1_mobile_owner_home.html' },
    ],
  },
  {
    route: '/login',
    appFile: 'src/app/pages/login.astro',
    domain: 'home',
    surface: 'Login',
    wireframes: ['F-LND1_desktop_landing_login.html'],
    status: 'mapped_pending_rebuild',
    notes: 'F-LND1 is imported as the landing/login role-routing face.',
    next: [
      { trigger: 'Sign in', route: 'role home', face: 'role-specific home face' },
      { trigger: 'Role demo continue', route: 'role home', face: 'role-specific home face' },
    ],
  },
  {
    route: '/portal',
    appFile: 'src/app/pages/portal/index.astro',
    domain: 'client_portal',
    surface: 'Client portal login',
    wireframes: ['F-CP1_desktop_client_portal.html'],
    status: 'client_surface',
    notes: 'Client-facing portal door, intentionally outside operator shell registry. Needs separate client-facing canon face.',
    next: [
      { trigger: 'Continue', route: '/portal/s/:token', face: 'client portal session face missing from repo' },
    ],
  },
  {
    route: '/portal/s/:token',
    appFile: 'src/app/pages/portal/s/[token].astro',
    domain: 'client_portal',
    surface: 'Client portal session',
    wireframes: ['F-CP1_desktop_client_portal.html', 'F-CPS1_mobile_client_project_status.html'],
    status: 'client_surface',
    notes: 'Client-facing session, outside operator shell.',
    next: [
      { trigger: 'Approve proposal/change', route: 'same route/API consequence', face: 'client portal session face missing from repo' },
    ],
  },
  {
    route: '/sub/portal',
    appFile: 'src/app/pages/sub/portal/index.astro',
    domain: 'people_admin_ops',
    surface: 'Sub portal login',
    wireframes: ['F-SH1_mobile_sub_home.html', 'F-SUB1_mobile_sub_portal.html'],
    status: 'client_surface',
    notes: 'Subcontractor-facing portal door. Registered separately from operator shell.',
    next: [
      { trigger: 'Continue', route: '/sub/portal/s/:token', face: 'F-SH1_mobile_sub_home.html' },
    ],
  },
  {
    route: '/sub/portal/s/:token',
    appFile: 'src/app/pages/sub/portal/s/[token].astro',
    domain: 'people_admin_ops',
    surface: 'Sub portal session',
    wireframes: ['F-SH1_mobile_sub_home.html', 'F-SUB1_mobile_sub_portal.html'],
    status: 'client_surface',
    notes: 'Sub assignment list.',
    next: [
      { trigger: 'Assignment', route: '/sub/portal/s/:token/a/:assignmentId', face: 'F-W1_mobile_work_order.html' },
    ],
  },
  {
    route: '/sub/portal/s/:token/a/:assignmentId',
    appFile: 'src/app/pages/sub/portal/s/[token]/a/[assignmentId].astro',
    domain: 'people_admin_ops',
    surface: 'Sub portal assignment',
    wireframes: ['F-W1_mobile_work_order.html'],
    status: 'client_surface',
    notes: 'Sub-facing assignment/work-order detail.',
    next: [
      { trigger: 'Back assignments', route: '/sub/portal/s/:token', face: 'F-SH1_mobile_sub_home.html' },
    ],
  },
];

export const WIREFRAME_REFERENCE_MAP: readonly WireframeReferenceEntry[] = [
  { wireframe: 'F-AA1_attention_artifact.html', intendedSurface: 'Shared attention artifact', intendedRoute: 'shared Home / On Me / review queue component', status: 'mapped_pending_rebuild', notes: 'Shared card grammar, not a standalone route.' },
  { wireframe: 'F-AD1_mobile_admin_landing.html', intendedSurface: 'Admin landing', intendedRoute: '/settings or /home/admin-ops', status: 'future_or_unrouted', notes: 'Admin landing is not a distinct live route yet.' },
  { wireframe: 'F-AD2_desktop_admin_landing.html', intendedSurface: 'Admin landing desktop', intendedRoute: '/settings or /home/admin-ops', status: 'future_or_unrouted', notes: 'Admin landing is not a distinct live route yet.' },
  { wireframe: 'F-BC1_mobile_bar_customization.html', intendedSurface: 'Bottom bar customization', intendedRoute: '/settings or /more', status: 'future_or_unrouted', notes: 'No live customization route.' },
  { wireframe: 'F-CA1a_mobile_client_archive.html', intendedSurface: 'Client archive', intendedRoute: '/clients?archive=1', status: 'future_or_unrouted', notes: 'Archive state is not a distinct live route.' },
  { wireframe: 'F-CA1b_desktop_client_archive.html', intendedSurface: 'Client archive desktop', intendedRoute: '/clients?archive=1', status: 'future_or_unrouted', notes: 'Archive state is not a distinct live route.' },
  { wireframe: 'F-HR1a_mobile_time_tracking.html', intendedSurface: 'Time tracking', intendedRoute: '/team-ops/time', status: 'future_or_unrouted', notes: 'No live time route.' },
  { wireframe: 'F-HR1b_desktop_time_tracking.html', intendedSurface: 'Time tracking desktop', intendedRoute: '/team-ops/time', status: 'future_or_unrouted', notes: 'No live time route.' },
  { wireframe: 'F-HR2_desktop_employee_docs.html', intendedSurface: 'Employee docs', intendedRoute: '/team-ops/docs', status: 'future_or_unrouted', notes: 'No live employee docs route.' },
  { wireframe: 'F-DL3_mobile_field_guidance_level.html', intendedSurface: 'Field guidance level', intendedRoute: '/settings or /home/field', status: 'future_or_unrouted', notes: 'Guidance level setting affects field-home/Daily Log behavior; no distinct live route yet.' },
  { wireframe: 'F-LD1a_mobile_lost_deals.html', intendedSurface: 'Lost deals', intendedRoute: '/sales?state=lost', status: 'future_or_unrouted', notes: 'Lost-deal state should live in Sales.' },
  { wireframe: 'F-LD1b_desktop_lost_deals.html', intendedSurface: 'Lost deals desktop', intendedRoute: '/sales?state=lost', status: 'future_or_unrouted', notes: 'Lost-deal state should live in Sales.' },
  { wireframe: 'F-MEM-RH_memory_system.html', intendedSurface: 'Right Hand memory model', intendedRoute: 'Right Hand working set / context resolver', status: 'mapped_pending_rebuild', notes: 'System model/reference face, not a page route.' },
  { wireframe: 'F-MK1_mobile_marketing_home.html', intendedSurface: 'Marketing home', intendedRoute: '/marketing', status: 'future_or_unrouted', notes: 'Marketing domain is not live-routed.' },
  { wireframe: 'F-MK2_desktop_marketing_home.html', intendedSurface: 'Marketing home desktop', intendedRoute: '/marketing', status: 'future_or_unrouted', notes: 'Marketing domain is not live-routed.' },
  { wireframe: 'F-MK3_mobile_reviews_referrals.html', intendedSurface: 'Reviews/referrals', intendedRoute: '/marketing/reviews', status: 'future_or_unrouted', notes: 'Marketing domain is not live-routed.' },
  { wireframe: 'F-MK4_desktop_reviews_referrals.html', intendedSurface: 'Reviews/referrals desktop', intendedRoute: '/marketing/reviews', status: 'future_or_unrouted', notes: 'Marketing domain is not live-routed.' },
  { wireframe: 'F-MK5_mobile_outreach_queue.html', intendedSurface: 'Outreach queue', intendedRoute: '/marketing/outreach', status: 'future_or_unrouted', notes: 'Marketing domain is not live-routed.' },
  { wireframe: 'F-MK6_desktop_outreach_queue.html', intendedSurface: 'Outreach queue desktop', intendedRoute: '/marketing/outreach', status: 'future_or_unrouted', notes: 'Marketing domain is not live-routed.' },
  { wireframe: 'F-MK7_mobile_attribution.html', intendedSurface: 'Attribution', intendedRoute: '/marketing/attribution', status: 'future_or_unrouted', notes: 'Marketing domain is not live-routed.' },
  { wireframe: 'F-MK8_desktop_attribution.html', intendedSurface: 'Attribution desktop', intendedRoute: '/marketing/attribution', status: 'future_or_unrouted', notes: 'Marketing domain is not live-routed.' },
  { wireframe: 'F-MK9_mobile_leads.html', intendedSurface: 'Leads', intendedRoute: '/marketing/leads or /sales', status: 'future_or_unrouted', notes: 'Lead intake currently folds into Sales.' },
  { wireframe: 'F-MK10_desktop_leads.html', intendedSurface: 'Leads desktop', intendedRoute: '/marketing/leads or /sales', status: 'future_or_unrouted', notes: 'Lead intake currently folds into Sales.' },
  { wireframe: 'F-ML1_mobile_project_media.html', intendedSurface: 'Project media', intendedRoute: '/projects/:id/media', status: 'future_or_unrouted', notes: 'Project media is currently a project lens/camera handoff, not a distinct route.' },
  { wireframe: 'F-ML2_desktop_project_media.html', intendedSurface: 'Project media desktop', intendedRoute: '/projects/:id/media', status: 'future_or_unrouted', notes: 'Project media is currently a project lens/camera handoff, not a distinct route.' },
  { wireframe: 'F-NAV1_normal_and_bubble_views.html', intendedSurface: 'Global shell / bubble view', intendedRoute: 'global shell chrome', status: 'mapped_pending_rebuild', notes: 'Global navigation reference, not a standalone route.' },
  { wireframe: 'F-NAV2_bottombar_center_vs_right.html', intendedSurface: 'Bottom bar center mic', intendedRoute: 'global bottom bar', status: 'mapped_pending_rebuild', notes: 'Bottom bar doctrine reference, not a standalone route.' },
  { wireframe: 'F-ORCH1_background_orchestration_flow.html', intendedSurface: 'Background orchestration', intendedRoute: 'background system flow', status: 'future_or_unrouted', notes: 'System orchestration reference, not an operator route.' },
  { wireframe: 'F-PA1a_mobile_project_archive.html', intendedSurface: 'Project archive', intendedRoute: '/projects?archive=1', status: 'future_or_unrouted', notes: 'Archive state is not a distinct live route.' },
  { wireframe: 'F-PA1b_desktop_project_archive.html', intendedSurface: 'Project archive desktop', intendedRoute: '/projects?archive=1', status: 'future_or_unrouted', notes: 'Archive state is not a distinct live route.' },
  { wireframe: 'F-PN1_desktop_project_notes.html', intendedSurface: 'Project notes', intendedRoute: '/projects/:id/notes', status: 'future_or_unrouted', notes: 'Project notes likely lives as a project lens; no distinct live route yet.' },
  { wireframe: 'F-PU1a_mobile_purchasing.html', intendedSurface: 'Purchasing', intendedRoute: '/money/purchasing or /projects/:id/purchasing', status: 'future_or_unrouted', notes: 'No live purchasing route.' },
  { wireframe: 'F-PU1b_desktop_purchasing.html', intendedSurface: 'Purchasing desktop', intendedRoute: '/money/purchasing or /projects/:id/purchasing', status: 'future_or_unrouted', notes: 'No live purchasing route.' },
  { wireframe: 'F-PU2_desktop_vendor_detail.html', intendedSurface: 'Vendor detail', intendedRoute: '/money/vendors/:id', status: 'future_or_unrouted', notes: 'No live vendor route.' },
  { wireframe: 'F-VC1_desktop_spend_card_framing.html', intendedSurface: 'Spend card framing', intendedRoute: '/money/spend-card', status: 'future_or_unrouted', notes: 'No live spend-card route.' },
  { wireframe: 'F-VW1_viewing_window_voice_editing.html', intendedSurface: 'Viewing window voice editing', intendedRoute: 'global Right Hand overlay', status: 'mapped_pending_rebuild', notes: 'Right Hand viewing-window interaction reference, not a standalone route.' },
];

export const EXTERNAL_OR_MISSING_CANON_FACES: readonly WireframeReferenceEntry[] = [
  { wireframe: 'RightHand_Fix_Review_2026-06-14.html', intendedSurface: 'Fix review integrated reference', intendedRoute: 'multiple spine surfaces', status: 'future_or_unrouted', notes: 'User-provided reference outside docs/wireframes/canon.' },
  { wireframe: 'F-PS1_mobile_pm_super_home.html', intendedSurface: 'PM / Super home conflict', intendedRoute: '/home/pm or /home/field', status: 'future_or_unrouted', notes: 'External Canon file reuses F-PS1, which already maps to project status in repo canon. Hold outside canon until the duplicate ID is resolved.' },
  { wireframe: 'F-SU2_desktop_super_home.html', intendedSurface: 'Superintendent home conflict', intendedRoute: '/home/field', status: 'future_or_unrouted', notes: 'External Canon file reuses F-SU2 with a different filename/title. Hold outside canon until the duplicate ID is resolved.' },
];
